/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::Page::exit() [sub_004CD474]
 * Virtual Address: 0x004CD474
 * File Offset:     0x003CD474
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004CD474
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x004CD474 in build/code.dec.bin
    bx lr
