/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::ThreadVariable<nn::nex::qList<nn::nex::SecurityContext>>::ResetValues() [sub_0011CBA0]
 * Virtual Address: 0x0011CBA0
 * File Offset:     0x0001CBA0
 * Size (bytes):    224
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0011CBA0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 224 bytes at VA 0x0011CBA0 in build/code.dec.bin
    bx lr
