/* DashDecomp — NODECOMPILED stub
 * Function: __rw::__rb_tree<nn::nex::LogicalClockTmpl<unsigned short>, std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>, __rw::__select1st<std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>, nn::nex::LogicalClockTmpl<unsigned short>>, std::less<nn::nex::LogicalClockTmpl<unsigned short>>, nn::nex::MemAllocator<std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>>>::_C_insert(__rw::__rw_rb_tree_node<nn::nex::MemAllocator<std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>>, std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>, nn::nex::LogicalClockTmpl<unsigned short>, __rw::__select1st<std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>, nn::nex::LogicalClockTmpl<unsigned short>>>*, __rw::__rw_rb_tree_node<nn::nex::MemAllocator<std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>>, std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>, nn::nex::LogicalClockTmpl<unsigned short>, __rw::__select1st<std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>, nn::nex::LogicalClockTmpl<unsigned short>>>*, const std::pair<const nn::nex::LogicalClockTmpl<unsigned short>, nn::nex::PacketOut*>&) [sub_005A5128]
 * Virtual Address: 0x005A5128
 * File Offset:     0x004A5128
 * Size (bytes):    948
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_005A5128
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 948 bytes at VA 0x005A5128 in build/code.dec.bin
    bx lr
