/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectSfcJumpBar::initObj() [sub_0035A500]
 * Virtual Address: 0x0035A500
 * File Offset:     0x0025A500
 * Size (bytes):    1188
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global initObj
.type   initObj, %function

initObj:  @ was sub_0035A500
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1188 bytes at VA 0x0035A500 in build/code.dec.bin
    bx lr
