/* DashDecomp — NODECOMPILED stub
 * Function: nn::applet::CTR::detail::APPLET::SetApplicationCpuTimeLimit(int, int) [sub_00104308]
 * Virtual Address: 0x00104308
 * File Offset:     0x00004308
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global SetApplicationCpuTimeLimit
.type   SetApplicationCpuTimeLimit, %function

SetApplicationCpuTimeLimit:  @ was sub_00104308
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x00104308 in build/code.dec.bin
    bx lr
