/* DashDecomp — NODECOMPILED stub
 * Function: Menu3D::GarageDirector::onSingleBattleKartStateFunc() [sub_003CFD98]
 * Virtual Address: 0x003CFD98
 * File Offset:     0x002CFD98
 * Size (bytes):    260
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global onSingleBattleKartStateFunc
.type   onSingleBattleKartStateFunc, %function

onSingleBattleKartStateFunc:  @ was sub_003CFD98
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 260 bytes at VA 0x003CFD98 in build/code.dec.bin
    bx lr
