/* DashDecomp — NODECOMPILED stub
 * Function: Menu3D::GarageDirector::preserveMii_(Mii::Face*, Mii::Icon*)
 * Virtual Address: 0x003CE2E0
 * File Offset:     0x002CE2E0
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global preserveMii
.type   preserveMii, %function

preserveMii:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x003CE2E0 in build/code.dec.bin
    bx lr
