/* DashDecomp — NODECOMPILED stub
 * Function: sub_005CB4AC
 * Virtual Address: 0x005CB4AC
 * File Offset:     0x004CB4AC
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005CB4AC
.type   sub_005CB4AC, %function

sub_005CB4AC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x005CB4AC in build/code.dec.bin
    bx lr
