/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::LastingTask::LastingTask__sub_object() [sub_004700E0]
 * Virtual Address: 0x004700E0
 * File Offset:     0x003700E0
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_004700E0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x004700E0 in build/code.dec.bin
    bx lr
