/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectNoteJumpBox::calc_InitialWaiting() [sub_00361DD0]
 * Virtual Address: 0x00361DD0
 * File Offset:     0x00261DD0
 * Size (bytes):    704
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global calc_InitialWaiting
.type   calc_InitialWaiting, %function

calc_InitialWaiting:  @ was sub_00361DD0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 704 bytes at VA 0x00361DD0 in build/code.dec.bin
    bx lr
