/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::DelegateSequence::finish(Sequence::Section::EFadeKind, unsigned) [sub_00495344]
 * Virtual Address: 0x00495344
 * File Offset:     0x00395344
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00495344
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x00495344 in build/code.dec.bin
    bx lr
