/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectAcSteam::initObj() [sub_0032788C]
 * Virtual Address: 0x0032788C
 * File Offset:     0x0022788C
 * Size (bytes):    228
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global initObj
.type   initObj, %function

initObj:  @ was sub_0032788C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 228 bytes at VA 0x0032788C in build/code.dec.bin
    bx lr
