/* DashDecomp — NODECOMPILED stub
 * Function: nn::os::Thread::SleepImpl(nn::fnd::TimeSpan)
 * Virtual Address: 0x001057F8
 * File Offset:     0x000057F8
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global SleepImpl
.type   SleepImpl, %function

SleepImpl:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x001057F8 in build/code.dec.bin
    bx lr
