/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::Model::Create(nw::gfx::SceneNode*, nw::gfx::res::ResSceneObject, const nw::gfx::Model::Description&, nw::os::IAllocator*) [sub_0025C6DC]
 * Virtual Address: 0x0025C6DC
 * File Offset:     0x0015C6DC
 * Size (bytes):    972
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0025C6DC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 972 bytes at VA 0x0025C6DC in build/code.dec.bin
    bx lr
