/* DashDecomp — NODECOMPILED stub
 * Function: __rw::__rb_tree<nn::nex::String, std::pair<const nn::nex::String, unsigned>, __rw::__select1st<std::pair<const nn::nex::String, unsigned>, nn::nex::String>, std::less<nn::nex::String>, nn::nex::MemAllocator<std::pair<const nn::nex::String, unsigned>>>::erase(__rw::__rw_tree_iter<std::pair<const nn::nex::String, unsigned>, int, std::pair<const nn::nex::String, unsigned>*, std::pair<const nn::nex::String, unsigned>&, __rw::__rw_rb_tree_node<nn::nex::MemAllocator<std::pair<const nn::nex::String, unsigned>>, std::pair<const nn::nex::String, unsigned>, nn::nex::String, __rw::__select1st<std::pair<const nn::nex::String, unsigned>, nn::nex::String>>>, __rw::__rw_tree_iter<std::pair<const nn::nex::String, unsigned>, int, std::pair<const nn::nex::String, unsigned>*, std::pair<const nn::nex::String, unsigned>&, __rw::__rw_rb_tree_node<nn::nex::MemAllocator<std::pair<const nn::nex::String, unsigned>>, std::pair<const nn::nex::String, unsigned>, nn::nex::String, __rw::__select1st<std::pair<const nn::nex::String, unsigned>, nn::nex::String>>>) [sub_005A7730]
 * Virtual Address: 0x005A7730
 * File Offset:     0x004A7730
 * Size (bytes):    1920
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_005A7730
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1920 bytes at VA 0x005A7730 in build/code.dec.bin
    bx lr
