/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectSfcTwistWayCollision::rejectFloor(const sead::Vector3<float>&, float, sead::Vector3<float>*, sead::Vector3<float>*, float*) const [sub_0050829C]
 * Virtual Address: 0x0050829C
 * File Offset:     0x0040829C
 * Size (bytes):    572
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0050829C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 572 bytes at VA 0x0050829C in build/code.dec.bin
    bx lr
