/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::internal::driver::HardwareManager::HardwareManager() [sub_0024D558]
 * Virtual Address: 0x0024D558
 * File Offset:     0x0014D558
 * Size (bytes):    300
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global HardwareManager
.type   HardwareManager, %function

HardwareManager:  @ was sub_0024D558
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 300 bytes at VA 0x0024D558 in build/code.dec.bin
    bx lr
