/* DashDecomp — NODECOMPILED stub
 * Function: nn::hid::CTR::detail::Ipc::EnableGyroscopeLow() [sub_001936DC]
 * Virtual Address: 0x001936DC
 * File Offset:     0x000936DC
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_001936DC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x001936DC in build/code.dec.bin
    bx lr
