/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectWiiCannon::getDTIClassStatic() [sub_00356038]
 * Virtual Address: 0x00356038
 * File Offset:     0x00256038
 * Size (bytes):    640
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

getDTIClassStatic:  @ was sub_00356038
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 640 bytes at VA 0x00356038 in build/code.dec.bin
    bx lr
