/* DashDecomp — NODECOMPILED stub
 * Function: nn::fs::CTR::MPCore::detail::FileServerArchive::Directory::Close() [sub_00165654]
 * Virtual Address: 0x00165654
 * File Offset:     0x00065654
 * Size (bytes):    304
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

Close:  @ was sub_00165654
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 304 bytes at VA 0x00165654 in build/code.dec.bin
    bx lr
