/* DashDecomp — NODECOMPILED stub
 * Function: System::CustomBufferSetting::toDefaultFrameBuffer() [sub_0044DCB0]
 * Virtual Address: 0x0044DCB0
 * File Offset:     0x0034DCB0
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0044DCB0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x0044DCB0 in build/code.dec.bin
    bx lr
