/* DashDecomp — NODECOMPILED stub
 * Function: UI::ResultBarTA::setLatest(bool) [sub_0014D788]
 * Virtual Address: 0x0014D788
 * File Offset:     0x0004D788
 * Size (bytes):    172
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0014D788
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 172 bytes at VA 0x0014D788 in build/code.dec.bin
    bx lr
