/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::_DS_DefaultCellParameter::AddSourceTo(nn::nex::Message*, nn::nex::Time, bool) [sub_00202CD8]
 * Virtual Address: 0x00202CD8
 * File Offset:     0x00102CD8
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00202CD8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x00202CD8 in build/code.dec.bin
    bx lr
