/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::MatchMakingClient::RegisterProtocols() [sub_0018A980]
 * Virtual Address: 0x0018A980
 * File Offset:     0x0008A980
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0018A980
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x0018A980 in build/code.dec.bin
    bx lr
