/* DashDecomp — NODECOMPILED stub
 * Function: nn::fs::CTR::GetSelfSystemMenuData(nn::CTR::SystemMenuData*) [sub_00185444]
 * Virtual Address: 0x00185444
 * File Offset:     0x00085444
 * Size (bytes):    716
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00185444
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 716 bytes at VA 0x00185444 in build/code.dec.bin
    bx lr
