/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectItemBoxTag::creator(Field::ObjectCreateArgument&) [sub_00388944]
 * Virtual Address: 0x00388944
 * File Offset:     0x00288944
 * Size (bytes):    164
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00388944
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 164 bytes at VA 0x00388944 in build/code.dec.bin
    bx lr
