/* DashDecomp — NODECOMPILED stub
 * Function: UI::ResultBattlePoint::getDTIClass() const [sub_0048C248]
 * Virtual Address: 0x0048C248
 * File Offset:     0x0038C248
 * Size (bytes):    652
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global getDTIClass
.type   getDTIClass, %function

getDTIClass:  @ was sub_0048C248
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 652 bytes at VA 0x0048C248 in build/code.dec.bin
    bx lr
