/* DashDecomp — NODECOMPILED stub
 * Function: nn::os::CriticalSection::ScopedLock::~ScopedLock() [sub_00105788]
 * Virtual Address: 0x00105788
 * File Offset:     0x00005788
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ScopedLock
.type   ScopedLock, %function

ScopedLock:  @ was sub_00105788
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x00105788 in build/code.dec.bin
    bx lr
