/* DashDecomp — NODECOMPILED stub
 * Function: nw::lyt::Material::Init() [sub_0026A5DC]
 * Virtual Address: 0x0026A5DC
 * File Offset:     0x0016A5DC
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0026A5DC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x0026A5DC in build/code.dec.bin
    bx lr
