/* DashDecomp — NODECOMPILED stub
 * Function: Net::NetworkBufferController::onReceived(int, int, unsigned char*, unsigned) [sub_002A4180]
 * Virtual Address: 0x002A4180
 * File Offset:     0x001A4180
 * Size (bytes):    392
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_002A4180
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 392 bytes at VA 0x002A4180 in build/code.dec.bin
    bx lr
