/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::ControlSlider::updatePosDefH(unsigned) [sub_0047F3A4]
 * Virtual Address: 0x0047F3A4
 * File Offset:     0x0037F3A4
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0047F3A4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x0047F3A4 in build/code.dec.bin
    bx lr
