/* DashDecomp — NODECOMPILED stub
 * Function: thunk{-160} to Field::ObjectKinoko::getDTIClass() const [sub_00520EE0]
 * Virtual Address: 0x00520EE0
 * File Offset:     0x00420EE0
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00520EE0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x00520EE0 in build/code.dec.bin
    bx lr
