/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DuplicatedObject::DuplicatedObject__sub_object() [sub_001A6464]
 * Virtual Address: 0x001A6464
 * File Offset:     0x000A6464
 * Size (bytes):    176
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

DuplicatedObject_sub_object:  @ was sub_001A6464
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 176 bytes at VA 0x001A6464 in build/code.dec.bin
    bx lr
