/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::DlgSeq::setOKSound_NoButton(Sound::SndSeEvent::EEvent) [sub_0047833C]
 * Virtual Address: 0x0047833C
 * File Offset:     0x0037833C
 * Size (bytes):    668
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global setOKSound_NoButton
.type   setOKSound_NoButton, %function

setOKSound_NoButton:  @ was sub_0047833C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 668 bytes at VA 0x0047833C in build/code.dec.bin
    bx lr
