/* DashDecomp — NODECOMPILED stub
 * Function: System::KDPadRecorder::calcRecord() [sub_00443278]
 * Virtual Address: 0x00443278
 * File Offset:     0x00343278
 * Size (bytes):    436
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00443278
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 436 bytes at VA 0x00443278 in build/code.dec.bin
    bx lr
