/* DashDecomp — NODECOMPILED stub
 * Function: UI::CursorItem::setCursorOff(bool) [sub_00141ECC]
 * Virtual Address: 0x00141ECC
 * File Offset:     0x00041ECC
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00141ECC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x00141ECC in build/code.dec.bin
    bx lr
