/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::Model::CreateMaterials(nw::os::IAllocator*) [sub_00230898]
 * Virtual Address: 0x00230898
 * File Offset:     0x00130898
 * Size (bytes):    464
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

CreateMaterials:  @ was sub_00230898
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 464 bytes at VA 0x00230898 in build/code.dec.bin
    bx lr
