/* DashDecomp — NODECOMPILED stub
 * Function: __cpp_initialize__aeabi_ [sub_0057CC7C]
 * Virtual Address: 0x0057CC7C
 * File Offset:     0x0047CC7C
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global cpp_initialize_aeabi
.type   cpp_initialize_aeabi, %function

cpp_initialize_aeabi:  @ was sub_0057CC7C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x0057CC7C in build/code.dec.bin
    bx lr
