/* DashDecomp — NODECOMPILED stub
 * Function: glUniform4fv [sub_00520288]
 * Virtual Address: 0x00520288
 * File Offset:     0x00420288
 * Size (bytes):    100
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global glUniform4fv
.type   glUniform4fv, %function

glUniform4fv:  @ was sub_00520288
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 100 bytes at VA 0x00520288 in build/code.dec.bin
    bx lr
