/* DashDecomp — NODECOMPILED stub
 * Function: sub_0056B79C
 * Virtual Address: 0x0056B79C
 * File Offset:     0x0046B79C
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0056B79C
.type   sub_0056B79C, %function

sub_0056B79C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x0056B79C in build/code.dec.bin
    bx lr
