/* DashDecomp — NODECOMPILED stub
 * Function: sub_00524720
 * Virtual Address: 0x00524720
 * File Offset:     0x00424720
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00524720
.type   sub_00524720, %function

sub_00524720:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x98, 0x0D, 0xFA, 0xEB, 0x10, 0x80, 0xBD, 0xE8
