/* DashDecomp — NODECOMPILED stub
 * Function: sub_00522188
 * Virtual Address: 0x00522188
 * File Offset:     0x00422188
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00522188
.type   sub_00522188, %function

sub_00522188:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x36, 0x1C, 0xF9, 0xEB, 0x10, 0x80, 0xBD, 0xE8
