/* DashDecomp — NODECOMPILED stub
 * Function: sub_00521F0C
 * Virtual Address: 0x00521F0C
 * File Offset:     0x00421F0C
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00521F0C
.type   sub_00521F0C, %function

sub_00521F0C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x00521F0C in build/code.dec.bin
    bx lr
