/* DashDecomp — NODECOMPILED stub
 * Function: sub_00525CC4
 * Virtual Address: 0x00525CC4
 * File Offset:     0x00425CC4
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00525CC4
.type   sub_00525CC4, %function

sub_00525CC4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x00525CC4 in build/code.dec.bin
    bx lr
