/* DashDecomp — NODECOMPILED stub
 * Function: sub_005228CC
 * Virtual Address: 0x005228CC
 * File Offset:     0x004228CC
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005228CC
.type   sub_005228CC, %function

sub_005228CC:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0xCE, 0x57, 0xF9, 0xEB, 0x10, 0x80, 0xBD, 0xE8
