/* DashDecomp — NODECOMPILED stub
 * Function: sub_00520BC8
 * Virtual Address: 0x00520BC8
 * File Offset:     0x00420BC8
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00520BC8
.type   sub_00520BC8, %function

sub_00520BC8:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0xFB, 0x95, 0xF8, 0xEB, 0x10, 0x80, 0xBD, 0xE8
