/* DashDecomp — NODECOMPILED stub
 * Function: sub_005242F4
 * Virtual Address: 0x005242F4
 * File Offset:     0x004242F4
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005242F4
.type   sub_005242F4, %function

sub_005242F4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x005242F4 in build/code.dec.bin
    bx lr
