/* DashDecomp — NODECOMPILED stub
 * Function: sub_00521C84
 * Virtual Address: 0x00521C84
 * File Offset:     0x00421C84
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00521C84
.type   sub_00521C84, %function

sub_00521C84:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x57, 0xDE, 0xF8, 0xEB, 0x10, 0x80, 0xBD, 0xE8
