/* DashDecomp — NODECOMPILED stub
 * Function: sub_005139AC
 * Virtual Address: 0x005139AC
 * File Offset:     0x004139AC
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005139AC
.type   sub_005139AC, %function

sub_005139AC:
    .byte 0x00, 0x10, 0x91, 0xE5, 0x10, 0x00, 0x9F, 0xE5, 0x81, 0x01, 0x80, 0xE0, 0xD0, 0x00, 0xC0, 0xE1
    .byte 0x01, 0x00, 0x80, 0xE0, 0xA0, 0x00, 0xA0, 0xE1, 0x1E, 0xFF, 0x2F, 0xE1
