/* DashDecomp — NODECOMPILED stub
 * Function: sub_0055330C
 * Virtual Address: 0x0055330C
 * File Offset:     0x0045330C
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0055330C
.type   sub_0055330C, %function

sub_0055330C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x0055330C in build/code.dec.bin
    bx lr
