/* DashDecomp — NODECOMPILED stub
 * Function: sub_0055A288
 * Virtual Address: 0x0055A288
 * File Offset:     0x0045A288
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0055A288
.type   sub_0055A288, %function

sub_0055A288:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x0055A288 in build/code.dec.bin
    bx lr
