/* DashDecomp — NODECOMPILED stub
 * Function: sub_005265FC
 * Virtual Address: 0x005265FC
 * File Offset:     0x004265FC
 * Size (bytes):    80
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005265FC
.type   sub_005265FC, %function

sub_005265FC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 80 bytes at VA 0x005265FC in build/code.dec.bin
    bx lr
