/* DashDecomp — NODECOMPILED stub
 * Function: sub_00523CAC
 * Virtual Address: 0x00523CAC
 * File Offset:     0x00423CAC
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00523CAC
.type   sub_00523CAC, %function

sub_00523CAC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x00523CAC in build/code.dec.bin
    bx lr
