/* DashDecomp — NODECOMPILED stub
 * Function: sub_0053CEB0
 * Virtual Address: 0x0053CEB0
 * File Offset:     0x0043CEB0
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0053CEB0
.type   sub_0053CEB0, %function

sub_0053CEB0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x0053CEB0 in build/code.dec.bin
    bx lr
