/* DashDecomp — NODECOMPILED stub
 * Function: sub_005349CC
 * Virtual Address: 0x005349CC
 * File Offset:     0x004349CC
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_005349CC
.type   sub_005349CC, %function

sub_005349CC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x005349CC in build/code.dec.bin
    bx lr
