/* DashDecomp — NODECOMPILED stub
 * Function: sub_00524A38
 * Virtual Address: 0x00524A38
 * File Offset:     0x00424A38
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00524A38
.type   sub_00524A38, %function

sub_00524A38:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x21, 0x30, 0xFA, 0xEB, 0x10, 0x80, 0xBD, 0xE8
