/* DashDecomp — NODECOMPILED stub
 * Function: sub_005240F0
 * Virtual Address: 0x005240F0
 * File Offset:     0x004240F0
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005240F0
.type   sub_005240F0, %function

sub_005240F0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x005240F0 in build/code.dec.bin
    bx lr
