/* DashDecomp — NODECOMPILED stub
 * Function: sead::RuntimeTypeInfo::Derive<sead::TaskBase>::isDerived(const sead::RuntimeTypeInfo::Interface*) const [sub_00571FCC]
 * Virtual Address: 0x00571FCC
 * File Offset:     0x00471FCC
 * Size (bytes):    184
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

isDerived:  @ was sub_00571FCC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 184 bytes at VA 0x00571FCC in build/code.dec.bin
    bx lr
