/* DashDecomp — NODECOMPILED stub
 * Function: System::ResourceList::find(const sead::SafeStringBase<char>&, int*, unsigned) [sub_004401B4]
 * Virtual Address: 0x004401B4
 * File Offset:     0x003401B4
 * Size (bytes):    328
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004401B4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 328 bytes at VA 0x004401B4 in build/code.dec.bin
    bx lr
