/* DashDecomp — NODECOMPILED stub
 * Function: sub_004D0A04
 * Virtual Address: 0x004D0A04
 * File Offset:     0x003D0A04
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004D0A04
.type   sub_004D0A04, %function

sub_004D0A04:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x004D0A04 in build/code.dec.bin
    bx lr
