/* DashDecomp — NODECOMPILED stub
 * Function: sub_00495524
 * Virtual Address: 0x00495524
 * File Offset:     0x00395524
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00495524
.type   sub_00495524, %function

sub_00495524:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x00495524 in build/code.dec.bin
    bx lr
