/* DashDecomp — NODECOMPILED stub
 * Function: sub_004AA2AC
 * Virtual Address: 0x004AA2AC
 * File Offset:     0x003AA2AC
 * Size (bytes):    332
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004AA2AC
.type   sub_004AA2AC, %function

sub_004AA2AC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 332 bytes at VA 0x004AA2AC in build/code.dec.bin
    bx lr
