/* DashDecomp — NODECOMPILED stub
 * Function: sub_005066DC
 * Virtual Address: 0x005066DC
 * File Offset:     0x004066DC
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005066DC
.type   sub_005066DC, %function

sub_005066DC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x005066DC in build/code.dec.bin
    bx lr
