/* DashDecomp — NODECOMPILED stub
 * Function: sub_004BDF70
 * Virtual Address: 0x004BDF70
 * File Offset:     0x003BDF70
 * Size (bytes):    184
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004BDF70
.type   sub_004BDF70, %function

sub_004BDF70:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 184 bytes at VA 0x004BDF70 in build/code.dec.bin
    bx lr
