/* DashDecomp — NODECOMPILED stub
 * Function: sub_004CB35C
 * Virtual Address: 0x004CB35C
 * File Offset:     0x003CB35C
 * Size (bytes):    92
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004CB35C
.type   sub_004CB35C, %function

sub_004CB35C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 92 bytes at VA 0x004CB35C in build/code.dec.bin
    bx lr
