/* DashDecomp — NODECOMPILED stub
 * Function: sub_00495F18
 * Virtual Address: 0x00495F18
 * File Offset:     0x00395F18
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00495F18
.type   sub_00495F18, %function

sub_00495F18:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x00, 0x40, 0xA0, 0xE1, 0x88, 0xD4, 0xFF, 0xEB, 0x04, 0x00, 0xA0, 0xE1
    .byte 0x10, 0x40, 0xBD, 0xE8, 0x00, 0x00, 0xA0, 0xE1
