/* DashDecomp — NODECOMPILED stub
 * Function: sub_0049D958
 * Virtual Address: 0x0049D958
 * File Offset:     0x0039D958
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0049D958
.type   sub_0049D958, %function

sub_0049D958:
    .byte 0x00, 0x10, 0xA0, 0xE3, 0x00, 0x10, 0x80, 0xE5, 0x04, 0x10, 0x80, 0xE5, 0x08, 0x10, 0x80, 0xE5
    .byte 0x10, 0x10, 0x80, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
