/* DashDecomp — NODECOMPILED stub
 * Function: sub_004F0C44
 * Virtual Address: 0x004F0C44
 * File Offset:     0x003F0C44
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004F0C44
.type   sub_004F0C44, %function

sub_004F0C44:
    .byte 0x00, 0x00, 0x90, 0xE5, 0xC0, 0x0F, 0xA0, 0xE1, 0x01, 0x00, 0x80, 0xE2, 0x1E, 0xFF, 0x2F, 0xE1
