/* DashDecomp — NODECOMPILED stub
 * Function: sub_0047E960
 * Virtual Address: 0x0047E960
 * File Offset:     0x0037E960
 * Size (bytes):    620
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0047E960
.type   sub_0047E960, %function

sub_0047E960:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 620 bytes at VA 0x0047E960 in build/code.dec.bin
    bx lr
