/* DashDecomp — NODECOMPILED stub
 * Function: sub_004F01B8
 * Virtual Address: 0x004F01B8
 * File Offset:     0x003F01B8
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004F01B8
.type   sub_004F01B8, %function


.section .text
.global sub_004F01B8
.type   sub_004F01B8, %function

sub_004F01B8:
    .byte 0x08, 0x10, 0xD0, 0xE5, 0x00, 0x00, 0x51, 0xE3, 0x01, 0x00, 0x00, 0x0A, 0x30, 0x00, 0x80, 0xE2
    .byte 0x3A, 0xFE, 0xFF, 0xEA, 0x1E, 0xFF, 0x2F, 0xE1
