/* DashDecomp — NODECOMPILED stub
 * Function: sub_004FE690
 * Virtual Address: 0x004FE690
 * File Offset:     0x003FE690
 * Size (bytes):    8
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004FE690
.type   sub_004FE690, %function

sub_004FE690:
    .byte 0x00, 0x00, 0x9F, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
