/* DashDecomp — NODECOMPILED stub
 * Function: sub_0047E8C4
 * Virtual Address: 0x0047E8C4
 * File Offset:     0x0037E8C4
 * Size (bytes):    132
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0047E8C4
.type   sub_0047E8C4, %function

sub_0047E8C4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 132 bytes at VA 0x0047E8C4 in build/code.dec.bin
    bx lr
