/* DashDecomp — NODECOMPILED stub
 * Function: sub_004F0C74
 * Virtual Address: 0x004F0C74
 * File Offset:     0x003F0C74
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004F0C74
.type   sub_004F0C74, %function

sub_004F0C74:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x004F0C74 in build/code.dec.bin
    bx lr
