/* DashDecomp — NODECOMPILED stub
 * Function: sub_004FAE14
 * Virtual Address: 0x004FAE14
 * File Offset:     0x003FAE14
 * Size (bytes):    120
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004FAE14
.type   sub_004FAE14, %function

sub_004FAE14:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 120 bytes at VA 0x004FAE14 in build/code.dec.bin
    bx lr
