/* DashDecomp — NODECOMPILED stub
 * Function: sub_004AB580
 * Virtual Address: 0x004AB580
 * File Offset:     0x003AB580
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004AB580
.type   sub_004AB580, %function

sub_004AB580:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x004AB580 in build/code.dec.bin
    bx lr
