/* DashDecomp — NODECOMPILED stub
 * Function: sub_00498090
 * Virtual Address: 0x00498090
 * File Offset:     0x00398090
 * Size (bytes):    156
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00498090
.type   sub_00498090, %function

sub_00498090:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 156 bytes at VA 0x00498090 in build/code.dec.bin
    bx lr
