/* DashDecomp — NODECOMPILED stub
 * Function: sub_004A0C68
 * Virtual Address: 0x004A0C68
 * File Offset:     0x003A0C68
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_004A0C68
.type   sub_004A0C68, %function

sub_004A0C68:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x004A0C68 in build/code.dec.bin
    bx lr
