/* DashDecomp — NODECOMPILED stub
 * Function: sub_004BE3EC
 * Virtual Address: 0x004BE3EC
 * File Offset:     0x003BE3EC
 * Size (bytes):    536
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004BE3EC
.type   sub_004BE3EC, %function

sub_004BE3EC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 536 bytes at VA 0x004BE3EC in build/code.dec.bin
    bx lr
