/* DashDecomp — NODECOMPILED stub
 * Function: sub_004EC904
 * Virtual Address: 0x004EC904
 * File Offset:     0x003EC904
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004EC904
.type   sub_004EC904, %function

sub_004EC904:
    .byte 0xD8, 0x03, 0xC0, 0xE1, 0x00, 0x00, 0x41, 0xE0, 0x40, 0x01, 0xA0, 0xE1, 0x1E, 0xFF, 0x2F, 0xE1
