/* DashDecomp — NODECOMPILED stub
 * Function: sub_0049F188
 * Virtual Address: 0x0049F188
 * File Offset:     0x0039F188
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0049F188
.type   sub_0049F188, %function

sub_0049F188:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x0049F188 in build/code.dec.bin
    bx lr
