/* DashDecomp — NODECOMPILED stub
 * Function: sub_004F0CA0
 * Virtual Address: 0x004F0CA0
 * File Offset:     0x003F0CA0
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004F0CA0
.type   sub_004F0CA0, %function

sub_004F0CA0:
    .byte 0x38, 0x00, 0x80, 0xE2, 0x05, 0x00, 0x90, 0xE8, 0x00, 0x20, 0x42, 0xE0, 0x42, 0x01, 0x51, 0xE1
    .byte 0x01, 0x01, 0x90, 0x37, 0x00, 0x00, 0xA0, 0x23, 0x1E, 0xFF, 0x2F, 0xE1
