/* DashDecomp — NODECOMPILED stub
 * Function: sub_004F0C8C
 * Virtual Address: 0x004F0C8C
 * File Offset:     0x003F0C8C
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004F0C8C
.type   sub_004F0C8C, %function

sub_004F0C8C:
    .byte 0x28, 0x00, 0x90, 0xE5, 0x00, 0x00, 0xD1, 0xE1, 0x01, 0x00, 0xA0, 0x03, 0x00, 0x00, 0xA0, 0x13
    .byte 0x1E, 0xFF, 0x2F, 0xE1
