/* DashDecomp — NODECOMPILED stub
 * Function: sub_004FF8F4
 * Virtual Address: 0x004FF8F4
 * File Offset:     0x003FF8F4
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004FF8F4
.type   sub_004FF8F4, %function

sub_004FF8F4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x004FF8F4 in build/code.dec.bin
    bx lr
