/* DashDecomp — NODECOMPILED stub
 * Function: sub_004FCA04
 * Virtual Address: 0x004FCA04
 * File Offset:     0x003FCA04
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004FCA04
.type   sub_004FCA04, %function

sub_004FCA04:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x004FCA04 in build/code.dec.bin
    bx lr
