/* DashDecomp — NODECOMPILED stub
 * Function: sub_004FC2FC
 * Virtual Address: 0x004FC2FC
 * File Offset:     0x003FC2FC
 * Size (bytes):    308
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004FC2FC
.type   sub_004FC2FC, %function

sub_004FC2FC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 308 bytes at VA 0x004FC2FC in build/code.dec.bin
    bx lr
