/* DashDecomp — NODECOMPILED stub
 * Function: sub_004F9E28
 * Virtual Address: 0x004F9E28
 * File Offset:     0x003F9E28
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004F9E28
.type   sub_004F9E28, %function

sub_004F9E28:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x004F9E28 in build/code.dec.bin
    bx lr
