/* DashDecomp — NODECOMPILED stub
 * Function: sub_004C0C84
 * Virtual Address: 0x004C0C84
 * File Offset:     0x003C0C84
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004C0C84
.type   sub_004C0C84, %function

sub_004C0C84:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x004C0C84 in build/code.dec.bin
    bx lr
