/* DashDecomp — NODECOMPILED stub
 * Function: sub_004EE028
 * Virtual Address: 0x004EE028
 * File Offset:     0x003EE028
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004EE028
.type   sub_004EE028, %function

sub_004EE028:
    .byte 0xB8, 0x01, 0xD0, 0xE1, 0x40, 0x00, 0x50, 0xE3, 0x01, 0x00, 0xA0, 0x03, 0x00, 0x00, 0xA0, 0x13
    .byte 0x1E, 0xFF, 0x2F, 0xE1
