/* DashDecomp — NODECOMPILED stub
 * Function: sub_004D9EEC
 * Virtual Address: 0x004D9EEC
 * File Offset:     0x003D9EEC
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004D9EEC
.type   sub_004D9EEC, %function

sub_004D9EEC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x004D9EEC in build/code.dec.bin
    bx lr
