/* DashDecomp — NODECOMPILED stub
 * Function: sub_004D6864
 * Virtual Address: 0x004D6864
 * File Offset:     0x003D6864
 * Size (bytes):    120
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004D6864
.type   sub_004D6864, %function

sub_004D6864:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 120 bytes at VA 0x004D6864 in build/code.dec.bin
    bx lr
