/* DashDecomp — NODECOMPILED stub
 * Function: Effect::GPUPtclStripeImpl::GPUPtclStripeImpl(sead::ExpHeap*, nn::gr::CTR::Shader*, CSVUtil::CSVParam*, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&, nn::gr::CTR::BindSymbolVSFloat&) [sub_003F0BF4]
 * Virtual Address: 0x003F0BF4
 * File Offset:     0x002F0BF4
 * Size (bytes):    488
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_003F0BF4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 488 bytes at VA 0x003F0BF4 in build/code.dec.bin
    bx lr
