/* DashDecomp — NODECOMPILED stub
 * Function: UI::BgRaceMapLoopControl::setType(UI::BgRaceMapLoopControl::EType) [sub_0016CD10]
 * Virtual Address: 0x0016CD10
 * File Offset:     0x0006CD10
 * Size (bytes):    212
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0016CD10
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 212 bytes at VA 0x0016CD10 in build/code.dec.bin
    bx lr
