/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DuplicatedObject::SendToAllDuplicas(nn::nex::Message*, unsigned) [sub_001CB0D4]
 * Virtual Address: 0x001CB0D4
 * File Offset:     0x000CB0D4
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_001CB0D4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x001CB0D4 in build/code.dec.bin
    bx lr
