/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::HostMigrationCallback::CallMethod(nn::nex::Operation*) [sub_001CABD8]
 * Virtual Address: 0x001CABD8
 * File Offset:     0x000CABD8
 * Size (bytes):    372
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global CallMethod
.type   CallMethod, %function

CallMethod:  @ was sub_001CABD8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 372 bytes at VA 0x001CABD8 in build/code.dec.bin
    bx lr
