/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::internal::driver::ChannelManager::~ChannelManager() [sub_002778EC]
 * Virtual Address: 0x002778EC
 * File Offset:     0x001778EC
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_002778EC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x002778EC in build/code.dec.bin
    bx lr
