/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::ThreadVariable<nn::nex::ObjectThreadRoot*>::ClearValue() [sub_00536A90]
 * Virtual Address: 0x00536A90
 * File Offset:     0x00436A90
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ClearValue
.type   ClearValue, %function

ClearValue:  @ was sub_00536A90
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x00536A90 in build/code.dec.bin
    bx lr
