/* DashDecomp — NODECOMPILED stub
 * Function: Render::LightManager::LightManager(nw::os::IAllocator*, sead::Heap*, int) [sub_00421B08]
 * Virtual Address: 0x00421B08
 * File Offset:     0x00321B08
 * Size (bytes):    404
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00421B08
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 404 bytes at VA 0x00421B08 in build/code.dec.bin
    bx lr
