/* DashDecomp — NODECOMPILED stub
 * Function: Kart::VehicleReact::reactBound(const sead::Vector3<float>&, float, float) [sub_002AF8D0]
 * Virtual Address: 0x002AF8D0
 * File Offset:     0x001AF8D0
 * Size (bytes):    832
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global reactBound
.type   reactBound, %function

reactBound:  @ was sub_002AF8D0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 832 bytes at VA 0x002AF8D0 in build/code.dec.bin
    bx lr
