/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectDinosaur::Partial::Partial() [sub_0033B360]
 * Virtual Address: 0x0033B360
 * File Offset:     0x0023B360
 * Size (bytes):    64
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Partial
.type   Partial, %function

Partial:  @ was sub_0033B360
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 64 bytes at VA 0x0033B360 in build/code.dec.bin
    bx lr
