/* DashDecomp — NODECOMPILED stub
 * Function: Camera::ClipData::updateData(const Camera::CameraBase&) [sub_003AD534]
 * Virtual Address: 0x003AD534
 * File Offset:     0x002AD534
 * Size (bytes):    256
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global updateData
.type   updateData, %function

updateData:  @ was sub_003AD534
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 256 bytes at VA 0x003AD534 in build/code.dec.bin
    bx lr
