/* DashDecomp — NODECOMPILED stub
 * Function: Render::MultiCoverChecker::MultiCoverChecker() [sub_00426DCC]
 * Virtual Address: 0x00426DCC
 * File Offset:     0x00326DCC
 * Size (bytes):    172
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00426DCC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 172 bytes at VA 0x00426DCC in build/code.dec.bin
    bx lr
