/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::JobProcessFault::~JobProcessFault() [sub_0019B1E8]
 * Virtual Address: 0x0019B1E8
 * File Offset:     0x0009B1E8
 * Size (bytes):    544
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global JobProcessFault
.type   JobProcessFault, %function

JobProcessFault:  @ was sub_0019B1E8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 544 bytes at VA 0x0019B1E8 in build/code.dec.bin
    bx lr
