/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::SceneNode::Accept(nw::gfx::ISceneVisitor*) [sub_00239A9C]
 * Virtual Address: 0x00239A9C
 * File Offset:     0x00139A9C
 * Size (bytes):    216
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Accept
.type   Accept, %function

Accept:  @ was sub_00239A9C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 216 bytes at VA 0x00239A9C in build/code.dec.bin
    bx lr
