/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::SceneNode::CreateCallbacks(nw::os::IAllocator*) [sub_00239488]
 * Virtual Address: 0x00239488
 * File Offset:     0x00139488
 * Size (bytes):    300
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global CreateCallbacks
.type   CreateCallbacks, %function

CreateCallbacks:  @ was sub_00239488
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 300 bytes at VA 0x00239488 in build/code.dec.bin
    bx lr
