/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::SceneNode::Initialize(nw::os::IAllocator*) [sub_00238F34]
 * Virtual Address: 0x00238F34
 * File Offset:     0x00138F34
 * Size (bytes):    176
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Initialize
.type   Initialize, %function

Initialize:  @ was sub_00238F34
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 176 bytes at VA 0x00238F34 in build/code.dec.bin
    bx lr
