/* DashDecomp — NODECOMPILED stub
 * Function: Enemy::AIRankGroupTop::doChangeTargetRank(int) [sub_00336D14]
 * Virtual Address: 0x00336D14
 * File Offset:     0x00236D14
 * Size (bytes):    144
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00336D14
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 144 bytes at VA 0x00336D14 in build/code.dec.bin
    bx lr
