/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::PseudoSingleton::~PseudoSingleton() [sub_001C0A6C]
 * Virtual Address: 0x001C0A6C
 * File Offset:     0x000C0A6C
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_001C0A6C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x001C0A6C in build/code.dec.bin
    bx lr
