/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::RootResetTask::getDTIClass() const [sub_004BCDDC]
 * Virtual Address: 0x004BCDDC
 * File Offset:     0x003BCDDC
 * Size (bytes):    572
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global getDTIClass
.type   getDTIClass, %function

getDTIClass:  @ was sub_004BCDDC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 572 bytes at VA 0x004BCDDC in build/code.dec.bin
    bx lr
