/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::RootResetTask::RootResetTask() [sub_004828E0]
 * Virtual Address: 0x004828E0
 * File Offset:     0x003828E0
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_004828E0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x004828E0 in build/code.dec.bin
    bx lr
