/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectUgKuriboBoard::init_DefaultShadowOffset() [sub_003765EC]
 * Virtual Address: 0x003765EC
 * File Offset:     0x002765EC
 * Size (bytes):    476
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

init_DefaultShadowOffset:  @ was sub_003765EC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 476 bytes at VA 0x003765EC in build/code.dec.bin
    bx lr
