/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::TicketManager::Login(nn::nex::CallContext*, nn::nex::qResult*, const nn::nex::String&, const char*, unsigned*, nn::nex::RVConnectionData*, nn::nex::String*, nn::nex::AnyObjectHolder<nn::nex::Data, nn::nex::String>*) [sub_0018B390]
 * Virtual Address: 0x0018B390
 * File Offset:     0x0008B390
 * Size (bytes):    192
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Login
.type   Login, %function

Login:  @ was sub_0018B390
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 192 bytes at VA 0x0018B390 in build/code.dec.bin
    bx lr
