/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DOCore::~DOCore() [sub_001E82E8]
 * Virtual Address: 0x001E82E8
 * File Offset:     0x000E82E8
 * Size (bytes):    624
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

DOCore:  @ was sub_001E82E8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 624 bytes at VA 0x001E82E8 in build/code.dec.bin
    bx lr
