/* DashDecomp — NODECOMPILED stub
 * Function: UI::BgRaceMapControl::getRotDirY() const [sub_004E37DC]
 * Virtual Address: 0x004E37DC
 * File Offset:     0x003E37DC
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004E37DC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x004E37DC in build/code.dec.bin
    bx lr
