/* DashDecomp — NODECOMPILED stub
 * Function: Sound::SndActorBase::calcListenerDistSq(const sead::Vector3<float>&) [sub_0039B618]
 * Virtual Address: 0x0039B618
 * File Offset:     0x0029B618
 * Size (bytes):    164
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global calcListenerDistSq
.type   calcListenerDistSq, %function

calcListenerDistSq:  @ was sub_0039B618
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 164 bytes at VA 0x0039B618 in build/code.dec.bin
    bx lr
