/* DashDecomp — NODECOMPILED stub
 * Function: std::ctype<char>::~ctype() [sub_004C50C8]
 * Virtual Address: 0x004C50C8
 * File Offset:     0x003C50C8
 * Size (bytes):    304
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ctype
.type   ctype, %function

ctype:  @ was sub_004C50C8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 304 bytes at VA 0x004C50C8 in build/code.dec.bin
    bx lr
