/* DashDecomp — NODECOMPILED stub
 * Function: Enemy::PointParam::isAbleToMiniTurbo() const [sub_005066DC]
 * Virtual Address: 0x005066DC
 * File Offset:     0x004066DC
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_005066DC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x005066DC in build/code.dec.bin
    bx lr
