/* DashDecomp — NODECOMPILED stub
 * Function: nw::anim::res::ResAnim::IsFullBakedAnim() const [sub_004FE5B8]
 * Virtual Address: 0x004FE5B8
 * File Offset:     0x003FE5B8
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004FE5B8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x004FE5B8 in build/code.dec.bin
    bx lr
