/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::PacketQueue::~PacketQueue__deallocating() [sub_0019B5CC]
 * Virtual Address: 0x0019B5CC
 * File Offset:     0x0009B5CC
 * Size (bytes):    100
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0019B5CC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 100 bytes at VA 0x0019B5CC in build/code.dec.bin
    bx lr
