/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::PacketQueue::Queue(nn::nex::Packet*, bool) [sub_00174C44]
 * Virtual Address: 0x00174C44
 * File Offset:     0x00074C44
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Queue
.type   Queue, %function

Queue:  @ was sub_00174C44
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x00174C44 in build/code.dec.bin
    bx lr
