/* DashDecomp — NODECOMPILED stub
 * Function: nw::ut::FrameHeap::Free(int) [sub_0023AEBC]
 * Virtual Address: 0x0023AEBC
 * File Offset:     0x0013AEBC
 * Size (bytes):    144
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0023AEBC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 144 bytes at VA 0x0023AEBC in build/code.dec.bin
    bx lr
