/* DashDecomp — NODECOMPILED stub
 * Function: Effect::CamEnvParticleNoRot::resetParam() [sub_003F333C]
 * Virtual Address: 0x003F333C
 * File Offset:     0x002F333C
 * Size (bytes):    168
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_003F333C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 168 bytes at VA 0x003F333C in build/code.dec.bin
    bx lr
