/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::GetEnemyLevel() [sub_00480514]
 * Virtual Address: 0x00480514
 * File Offset:     0x00380514
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00480514
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x00480514 in build/code.dec.bin
    bx lr
