/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::ParallelSequence::getDTIClass() const [sub_004BF054]
 * Virtual Address: 0x004BF054
 * File Offset:     0x003BF054
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

getDTIClass:  @ was sub_004BF054
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x004BF054 in build/code.dec.bin
    bx lr
