/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::ObjDupProtocol::ParseSpecificMessage(nn::nex::Message*, unsigned, bool)::sub__1 [sub_00191340]
 * Virtual Address: 0x00191340
 * File Offset:     0x00091340
 * Size (bytes):    8
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_00191340
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 8 bytes at VA 0x00191340 in build/code.dec.bin
    bx lr
