/* DashDecomp — NODECOMPILED stub
 * Function: Sound::SndLoader::setExtGroupAddress(int) [sub_003D942C]
 * Virtual Address: 0x003D942C
 * File Offset:     0x002D942C
 * Size (bytes):    272
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_003D942C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 272 bytes at VA 0x003D942C in build/code.dec.bin
    bx lr
