/* DashDecomp — NODECOMPILED stub
 * Function: Sound::SndSyncBgm::setSyncSeqVolume(float, int) [sub_003998AC]
 * Virtual Address: 0x003998AC
 * File Offset:     0x002998AC
 * Size (bytes):    864
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global setSyncSeqVolume
.type   setSyncSeqVolume, %function

setSyncSeqVolume:  @ was sub_003998AC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 864 bytes at VA 0x003998AC in build/code.dec.bin
    bx lr
