/* DashDecomp — NODECOMPILED stub
 * Function: UI::BgRaceMapItemControl::~BgRaceMapItemControl__deallocating() [sub_0016CBF8]
 * Virtual Address: 0x0016CBF8
 * File Offset:     0x0006CBF8
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_0016CBF8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x0016CBF8 in build/code.dec.bin
    bx lr
