/* DashDecomp — NODECOMPILED stub
 * Function: sub_003098BC
 * Virtual Address: 0x003098BC
 * File Offset:     0x002098BC
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003098BC
.type   sub_003098BC, %function

sub_003098BC:
    .byte 0x00, 0x00, 0x90, 0xE5, 0x00, 0x00, 0x50, 0xE3, 0x00, 0x00, 0x00, 0x0A, 0x76, 0x9A, 0xFD, 0xEA
    .byte 0x1E, 0xFF, 0x2F, 0xE1
