/* DashDecomp — NODECOMPILED stub
 * Function: sub_00333358
 * Virtual Address: 0x00333358
 * File Offset:     0x00233358
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00333358
.type   sub_00333358, %function

sub_00333358:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00333358 in build/code.dec.bin
    bx lr
