/* DashDecomp — NODECOMPILED stub
 * Function: sub_002B0434
 * Virtual Address: 0x002B0434
 * File Offset:     0x001B0434
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002B0434
.type   sub_002B0434, %function

sub_002B0434:
    .byte 0x1E, 0xFF, 0x2F, 0xE1
