/* DashDecomp — NODECOMPILED stub
 * Function: sub_0030E2D0
 * Virtual Address: 0x0030E2D0
 * File Offset:     0x0020E2D0
 * Size (bytes):    192
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0030E2D0
.type   sub_0030E2D0, %function

sub_0030E2D0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 192 bytes at VA 0x0030E2D0 in build/code.dec.bin
    bx lr
