/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C6770
 * Virtual Address: 0x002C6770
 * File Offset:     0x001C6770
 * Size (bytes):    504
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C6770
.type   sub_002C6770, %function

sub_002C6770:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 504 bytes at VA 0x002C6770 in build/code.dec.bin
    bx lr
