/* DashDecomp — NODECOMPILED stub
 * Function: sub_002A4580
 * Virtual Address: 0x002A4580
 * File Offset:     0x001A4580
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_002A4580
.type   sub_002A4580, %function

sub_002A4580:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x002A4580 in build/code.dec.bin
    bx lr
