/* DashDecomp — NODECOMPILED stub
 * Function: sub_002A4970
 * Virtual Address: 0x002A4970
 * File Offset:     0x001A4970
 * Size (bytes):    92
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002A4970
.type   sub_002A4970, %function

sub_002A4970:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 92 bytes at VA 0x002A4970 in build/code.dec.bin
    bx lr
