/* DashDecomp — NODECOMPILED stub
 * Function: sub_00303864
 * Virtual Address: 0x00303864
 * File Offset:     0x00203864
 * Size (bytes):    280
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00303864
.type   sub_00303864, %function

sub_00303864:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 280 bytes at VA 0x00303864 in build/code.dec.bin
    bx lr
