/* DashDecomp — NODECOMPILED stub
 * Function: sub_002A32FC
 * Virtual Address: 0x002A32FC
 * File Offset:     0x001A32FC
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002A32FC
.type   sub_002A32FC, %function

sub_002A32FC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x002A32FC in build/code.dec.bin
    bx lr
