/* DashDecomp — NODECOMPILED stub
 * Function: sub_00334A54
 * Virtual Address: 0x00334A54
 * File Offset:     0x00234A54
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00334A54
.type   sub_00334A54, %function

sub_00334A54:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x00334A54 in build/code.dec.bin
    bx lr
