/* DashDecomp — NODECOMPILED stub
 * Function: sub_00300630
 * Virtual Address: 0x00300630
 * File Offset:     0x00200630
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00300630
.type   sub_00300630, %function

sub_00300630:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x00300630 in build/code.dec.bin
    bx lr
