/* DashDecomp — NODECOMPILED stub
 * Function: sub_002B3FDC
 * Virtual Address: 0x002B3FDC
 * File Offset:     0x001B3FDC
 * Size (bytes):    148
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002B3FDC
.type   sub_002B3FDC, %function

sub_002B3FDC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 148 bytes at VA 0x002B3FDC in build/code.dec.bin
    bx lr
