/* DashDecomp — NODECOMPILED stub
 * Function: sub_002F505C
 * Virtual Address: 0x002F505C
 * File Offset:     0x001F505C
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002F505C
.type   sub_002F505C, %function

sub_002F505C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x002F505C in build/code.dec.bin
    bx lr
