/* DashDecomp — NODECOMPILED stub
 * Function: sub_003463C0
 * Virtual Address: 0x003463C0
 * File Offset:     0x002463C0
 * Size (bytes):    408
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003463C0
.type   sub_003463C0, %function

sub_003463C0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 408 bytes at VA 0x003463C0 in build/code.dec.bin
    bx lr
