/* DashDecomp — NODECOMPILED stub
 * Function: sub_00357780
 * Virtual Address: 0x00357780
 * File Offset:     0x00257780
 * Size (bytes):    408
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00357780
.type   sub_00357780, %function

sub_00357780:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 408 bytes at VA 0x00357780 in build/code.dec.bin
    bx lr
