/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C9698
 * Virtual Address: 0x002C9698
 * File Offset:     0x001C9698
 * Size (bytes):    248
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C9698
.type   sub_002C9698, %function

sub_002C9698:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 248 bytes at VA 0x002C9698 in build/code.dec.bin
    bx lr
