/* DashDecomp — NODECOMPILED stub
 * Function: sub_002810AC
 * Virtual Address: 0x002810AC
 * File Offset:     0x001810AC
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002810AC
.type   sub_002810AC, %function

sub_002810AC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x002810AC in build/code.dec.bin
    bx lr
