/* DashDecomp — NODECOMPILED stub
 * Function: sub_00282FD8
 * Virtual Address: 0x00282FD8
 * File Offset:     0x00182FD8
 * Size (bytes):    164
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00282FD8
.type   sub_00282FD8, %function

sub_00282FD8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 164 bytes at VA 0x00282FD8 in build/code.dec.bin
    bx lr
