/* DashDecomp — NODECOMPILED stub
 * Function: sub_0028F498
 * Virtual Address: 0x0028F498
 * File Offset:     0x0018F498
 * Size (bytes):    212
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0028F498
.type   sub_0028F498, %function

sub_0028F498:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 212 bytes at VA 0x0028F498 in build/code.dec.bin
    bx lr
