/* DashDecomp — NODECOMPILED stub
 * Function: sub_002DA380
 * Virtual Address: 0x002DA380
 * File Offset:     0x001DA380
 * Size (bytes):    160
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002DA380
.type   sub_002DA380, %function

sub_002DA380:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 160 bytes at VA 0x002DA380 in build/code.dec.bin
    bx lr
