/* DashDecomp — NODECOMPILED stub
 * Function: sub_0037151C
 * Virtual Address: 0x0037151C
 * File Offset:     0x0027151C
 * Size (bytes):    460
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0037151C
.type   sub_0037151C, %function

sub_0037151C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 460 bytes at VA 0x0037151C in build/code.dec.bin
    bx lr
