/* DashDecomp — NODECOMPILED stub
 * Function: sub_002E0A1C
 * Virtual Address: 0x002E0A1C
 * File Offset:     0x001E0A1C
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002E0A1C
.type   sub_002E0A1C, %function

sub_002E0A1C:
    .byte 0x01, 0x0A, 0x80, 0xE2, 0x68, 0x11, 0xD0, 0xE5, 0x0A, 0x10, 0x41, 0xE2, 0x05, 0x00, 0x51, 0xE3
    .byte 0x01, 0x10, 0xA0, 0x93, 0xD4, 0x11, 0xC0, 0x95, 0x1E, 0xFF, 0x2F, 0xE1
