/* DashDecomp — NODECOMPILED stub
 * Function: sub_0030EC90
 * Virtual Address: 0x0030EC90
 * File Offset:     0x0020EC90
 * Size (bytes):    868
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0030EC90
.type   sub_0030EC90, %function

sub_0030EC90:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 868 bytes at VA 0x0030EC90 in build/code.dec.bin
    bx lr
