/* DashDecomp — NODECOMPILED stub
 * Function: sub_002B2E04
 * Virtual Address: 0x002B2E04
 * File Offset:     0x001B2E04
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002B2E04
.type   sub_002B2E04, %function

sub_002B2E04:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x002B2E04 in build/code.dec.bin
    bx lr
