/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C7668
 * Virtual Address: 0x002C7668
 * File Offset:     0x001C7668
 * Size (bytes):    112
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C7668
.type   sub_002C7668, %function

sub_002C7668:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 112 bytes at VA 0x002C7668 in build/code.dec.bin
    bx lr
