/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C0030
 * Virtual Address: 0x002C0030
 * File Offset:     0x001C0030
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C0030
.type   sub_002C0030, %function

sub_002C0030:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x002C0030 in build/code.dec.bin
    bx lr
