/* DashDecomp — NODECOMPILED stub
 * Function: sub_0037EB8C
 * Virtual Address: 0x0037EB8C
 * File Offset:     0x0027EB8C
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0037EB8C
.type   sub_0037EB8C, %function

sub_0037EB8C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x0037EB8C in build/code.dec.bin
    bx lr
