/* DashDecomp — NODECOMPILED stub
 * Function: sub_00338A6C
 * Virtual Address: 0x00338A6C
 * File Offset:     0x00238A6C
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00338A6C
.type   sub_00338A6C, %function

sub_00338A6C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x00338A6C in build/code.dec.bin
    bx lr
