/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C4B5C
 * Virtual Address: 0x002C4B5C
 * File Offset:     0x001C4B5C
 * Size (bytes):    180
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C4B5C
.type   sub_002C4B5C, %function

sub_002C4B5C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 180 bytes at VA 0x002C4B5C in build/code.dec.bin
    bx lr
