/* DashDecomp — NODECOMPILED stub
 * Function: sub_002AB608
 * Virtual Address: 0x002AB608
 * File Offset:     0x001AB608
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002AB608
.type   sub_002AB608, %function

sub_002AB608:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x002AB608 in build/code.dec.bin
    bx lr
