/* DashDecomp — NODECOMPILED stub
 * Function: sub_00341260
 * Virtual Address: 0x00341260
 * File Offset:     0x00241260
 * Size (bytes):    124
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00341260
.type   sub_00341260, %function

sub_00341260:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 124 bytes at VA 0x00341260 in build/code.dec.bin
    bx lr
