/* DashDecomp — NODECOMPILED stub
 * Function: sub_003478BC
 * Virtual Address: 0x003478BC
 * File Offset:     0x002478BC
 * Size (bytes):    976
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003478BC
.type   sub_003478BC, %function

sub_003478BC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 976 bytes at VA 0x003478BC in build/code.dec.bin
    bx lr
