/* DashDecomp — NODECOMPILED stub
 * Function: sub_00303DC0
 * Virtual Address: 0x00303DC0
 * File Offset:     0x00203DC0
 * Size (bytes):    556
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00303DC0
.type   sub_00303DC0, %function

sub_00303DC0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 556 bytes at VA 0x00303DC0 in build/code.dec.bin
    bx lr
