/* DashDecomp — NODECOMPILED stub
 * Function: sub_002A2C54
 * Virtual Address: 0x002A2C54
 * File Offset:     0x001A2C54
 * Size (bytes):    276
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002A2C54
.type   sub_002A2C54, %function

sub_002A2C54:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 276 bytes at VA 0x002A2C54 in build/code.dec.bin
    bx lr
