/* DashDecomp — NODECOMPILED stub
 * Function: sub_00289978
 * Virtual Address: 0x00289978
 * File Offset:     0x00189978
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00289978
.type   sub_00289978, %function

sub_00289978:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x00289978 in build/code.dec.bin
    bx lr
