/* DashDecomp — NODECOMPILED stub
 * Function: sub_002DE1A8
 * Virtual Address: 0x002DE1A8
 * File Offset:     0x001DE1A8
 * Size (bytes):    1372
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002DE1A8
.type   sub_002DE1A8, %function

sub_002DE1A8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1372 bytes at VA 0x002DE1A8 in build/code.dec.bin
    bx lr
