/* DashDecomp — NODECOMPILED stub
 * Function: sub_00308D60
 * Virtual Address: 0x00308D60
 * File Offset:     0x00208D60
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00308D60
.type   sub_00308D60, %function

sub_00308D60:
    .byte 0x04, 0x10, 0x9F, 0xE5, 0x00, 0x10, 0x80, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
