/* DashDecomp — NODECOMPILED stub
 * Function: sub_002D6A7C
 * Virtual Address: 0x002D6A7C
 * File Offset:     0x001D6A7C
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_002D6A7C
.type   sub_002D6A7C, %function

sub_002D6A7C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x002D6A7C in build/code.dec.bin
    bx lr
