/* DashDecomp — NODECOMPILED stub
 * Function: sub_0036FDD0
 * Virtual Address: 0x0036FDD0
 * File Offset:     0x0026FDD0
 * Size (bytes):    312
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0036FDD0
.type   sub_0036FDD0, %function

sub_0036FDD0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 312 bytes at VA 0x0036FDD0 in build/code.dec.bin
    bx lr
