/* DashDecomp — NODECOMPILED stub
 * Function: sub_002B7F1C
 * Virtual Address: 0x002B7F1C
 * File Offset:     0x001B7F1C
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002B7F1C
.type   sub_002B7F1C, %function

sub_002B7F1C:
    .byte 0x04, 0x00, 0x9F, 0xE5, 0x04, 0x00, 0x90, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
