/* DashDecomp — NODECOMPILED stub
 * Function: sub_002F3338
 * Virtual Address: 0x002F3338
 * File Offset:     0x001F3338
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002F3338
.type   sub_002F3338, %function

sub_002F3338:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x002F3338 in build/code.dec.bin
    bx lr
