/* DashDecomp — NODECOMPILED stub
 * Function: sub_00328584
 * Virtual Address: 0x00328584
 * File Offset:     0x00228584
 * Size (bytes):    100
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00328584
.type   sub_00328584, %function

sub_00328584:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 100 bytes at VA 0x00328584 in build/code.dec.bin
    bx lr
