/* DashDecomp — NODECOMPILED stub
 * Function: sub_00309A1C
 * Virtual Address: 0x00309A1C
 * File Offset:     0x00209A1C
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00309A1C
.type   sub_00309A1C, %function

sub_00309A1C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x00309A1C in build/code.dec.bin
    bx lr
