/* DashDecomp — NODECOMPILED stub
 * Function: sub_002D43A0
 * Virtual Address: 0x002D43A0
 * File Offset:     0x001D43A0
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002D43A0
.type   sub_002D43A0, %function

sub_002D43A0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x002D43A0 in build/code.dec.bin
    bx lr
