/* DashDecomp — NODECOMPILED stub
 * Function: sub_0029B80C
 * Virtual Address: 0x0029B80C
 * File Offset:     0x0019B80C
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0029B80C
.type   sub_0029B80C, %function

sub_0029B80C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x0029B80C in build/code.dec.bin
    bx lr
