/* DashDecomp — NODECOMPILED stub
 * Function: sub_002B978C
 * Virtual Address: 0x002B978C
 * File Offset:     0x001B978C
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002B978C
.type   sub_002B978C, %function

sub_002B978C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x002B978C in build/code.dec.bin
    bx lr
