/* DashDecomp — NODECOMPILED stub
 * Function: sub_002A780E
 * Virtual Address: 0x002A780E
 * File Offset:     0x001A780E
 * Size (bytes):    16466
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_002A780E
.type   sub_002A780E, %function

sub_002A780E:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16466 bytes at VA 0x002A780E in build/code.dec.bin
    bx lr
