/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C3734
 * Virtual Address: 0x002C3734
 * File Offset:     0x001C3734
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C3734
.type   sub_002C3734, %function

sub_002C3734:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x002C3734 in build/code.dec.bin
    bx lr
