/* DashDecomp — NODECOMPILED stub
 * Function: sub_00319AC0
 * Virtual Address: 0x00319AC0
 * File Offset:     0x00219AC0
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00319AC0
.type   sub_00319AC0, %function

sub_00319AC0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x00319AC0 in build/code.dec.bin
    bx lr
