/* DashDecomp — NODECOMPILED stub
 * Function: sub_00350634
 * Virtual Address: 0x00350634
 * File Offset:     0x00250634
 * Size (bytes):    432
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00350634
.type   sub_00350634, %function

sub_00350634:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 432 bytes at VA 0x00350634 in build/code.dec.bin
    bx lr
