/* DashDecomp — NODECOMPILED stub
 * Function: sub_002E6B7E
 * Virtual Address: 0x002E6B7E
 * File Offset:     0x001E6B7E
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_002E6B7E
.type   sub_002E6B7E, %function

sub_002E6B7E:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x002E6B7E in build/code.dec.bin
    bx lr
