/* DashDecomp — NODECOMPILED stub
 * Function: sub_0037A6DC
 * Virtual Address: 0x0037A6DC
 * File Offset:     0x0027A6DC
 * Size (bytes):    168
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0037A6DC
.type   sub_0037A6DC, %function

sub_0037A6DC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 168 bytes at VA 0x0037A6DC in build/code.dec.bin
    bx lr
