/* DashDecomp — NODECOMPILED stub
 * Function: sub_00282AE0
 * Virtual Address: 0x00282AE0
 * File Offset:     0x00182AE0
 * Size (bytes):    892
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00282AE0
.type   sub_00282AE0, %function

sub_00282AE0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 892 bytes at VA 0x00282AE0 in build/code.dec.bin
    bx lr
