/* DashDecomp — NODECOMPILED stub
 * Function: sub_00333B3C
 * Virtual Address: 0x00333B3C
 * File Offset:     0x00233B3C
 * Size (bytes):    308
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00333B3C
.type   sub_00333B3C, %function

sub_00333B3C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 308 bytes at VA 0x00333B3C in build/code.dec.bin
    bx lr
