/* DashDecomp — NODECOMPILED stub
 * Function: sub_00320D8C
 * Virtual Address: 0x00320D8C
 * File Offset:     0x00220D8C
 * Size (bytes):    1128
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00320D8C
.type   sub_00320D8C, %function

sub_00320D8C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1128 bytes at VA 0x00320D8C in build/code.dec.bin
    bx lr
