/* DashDecomp — NODECOMPILED stub
 * Function: sub_002F7BEC
 * Virtual Address: 0x002F7BEC
 * File Offset:     0x001F7BEC
 * Size (bytes):    712
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002F7BEC
.type   sub_002F7BEC, %function

sub_002F7BEC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 712 bytes at VA 0x002F7BEC in build/code.dec.bin
    bx lr
