/* DashDecomp — NODECOMPILED stub
 * Function: sub_002D49C4
 * Virtual Address: 0x002D49C4
 * File Offset:     0x001D49C4
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002D49C4
.type   sub_002D49C4, %function

sub_002D49C4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x002D49C4 in build/code.dec.bin
    bx lr
