/* DashDecomp — NODECOMPILED stub
 * Function: sub_002AF314
 * Virtual Address: 0x002AF314
 * File Offset:     0x001AF314
 * Size (bytes):    92
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002AF314
.type   sub_002AF314, %function

sub_002AF314:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 92 bytes at VA 0x002AF314 in build/code.dec.bin
    bx lr
