/* DashDecomp — NODECOMPILED stub
 * Function: sub_002D2360
 * Virtual Address: 0x002D2360
 * File Offset:     0x001D2360
 * Size (bytes):    288
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002D2360
.type   sub_002D2360, %function

sub_002D2360:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 288 bytes at VA 0x002D2360 in build/code.dec.bin
    bx lr
