/* DashDecomp — NODECOMPILED stub
 * Function: sub_002C4688
 * Virtual Address: 0x002C4688
 * File Offset:     0x001C4688
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002C4688
.type   sub_002C4688, %function

sub_002C4688:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x002C4688 in build/code.dec.bin
    bx lr
