/* DashDecomp — NODECOMPILED stub
 * Function: sub_002ABAE0
 * Virtual Address: 0x002ABAE0
 * File Offset:     0x001ABAE0
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002ABAE0
.type   sub_002ABAE0, %function

sub_002ABAE0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x002ABAE0 in build/code.dec.bin
    bx lr
