/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::ProtocolRequestBroker::DispatchLocalRMC(nn::nex::Message*, nn::nex::ClientProtocol*, nn::nex::ServerProtocol*, nn::nex::EndPoint*) [sub_001CE054]
 * Virtual Address: 0x001CE054
 * File Offset:     0x000CE054
 * Size (bytes):    232
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global DispatchLocalRMC
.type   DispatchLocalRMC, %function

DispatchLocalRMC:  @ was sub_001CE054
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 232 bytes at VA 0x001CE054 in build/code.dec.bin
    bx lr
