/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectCmnTreeNoHitBase::ObjectCmnTreeNoHitBase(const Field::ObjectCreateArgument&, Field::eMapdataGeoObjID) [sub_0037E0AC]
 * Virtual Address: 0x0037E0AC
 * File Offset:     0x0027E0AC
 * Size (bytes):    268
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

ObjectCmnTreeNoHitBase:  @ was sub_0037E0AC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 268 bytes at VA 0x0037E0AC in build/code.dec.bin
    bx lr
