/* DashDecomp — NODECOMPILED stub
 * Function: sead::DirectProjection::DirectProjection() [sub_003101D0]
 * Virtual Address: 0x003101D0
 * File Offset:     0x002101D0
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_003101D0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x003101D0 in build/code.dec.bin
    bx lr
