/* DashDecomp — NODECOMPILED stub
 * Function: UI::BaseMenuButtonControl::AnimationDefine_TouchSelectFade::defineAnimation() [sub_0011C5E4]
 * Virtual Address: 0x0011C5E4
 * File Offset:     0x0001C5E4
 * Size (bytes):    200
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0011C5E4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 200 bytes at VA 0x0011C5E4 in build/code.dec.bin
    bx lr
