/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::MenuChannel_Top::CursorCalc::move(int, int, bool) [sub_0043FA90]
 * Virtual Address: 0x0043FA90
 * File Offset:     0x0033FA90
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global move
.type   move, %function

move:  @ was sub_0043FA90
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x0043FA90 in build/code.dec.bin
    bx lr
