/* DashDecomp — NODECOMPILED stub
 * Function: UI::SlotSelect::step(float) [sub_00131988]
 * Virtual Address: 0x00131988
 * File Offset:     0x00031988
 * Size (bytes):    984
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global step
.type   step, %function

step:  @ was sub_00131988
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 984 bytes at VA 0x00131988 in build/code.dec.bin
    bx lr
