/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectDokan::setReaction_fromKart(Field::EGHTReaction, Field::eObjectReactType, Kart::VehicleReact*) [sub_00315D34]
 * Virtual Address: 0x00315D34
 * File Offset:     0x00215D34
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

setReaction_fromKart:  @ was sub_00315D34
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x00315D34 in build/code.dec.bin
    bx lr
