/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectBcLavaFlow::getDTIClassStatic() [sub_003581C0]
 * Virtual Address: 0x003581C0
 * File Offset:     0x002581C0
 * Size (bytes):    416
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

getDTIClassStatic:  @ was sub_003581C0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 416 bytes at VA 0x003581C0 in build/code.dec.bin
    bx lr
