/* DashDecomp — NODECOMPILED stub
 * Function: nn::http::detail::LibManager::~LibManager() [sub_002049C4]
 * Virtual Address: 0x002049C4
 * File Offset:     0x001049C4
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global LibManager
.type   LibManager, %function

LibManager:  @ was sub_002049C4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x002049C4 in build/code.dec.bin
    bx lr
