/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DirectTransport::SendUnreliableAll(unsigned char*, unsigned) [sub_00198474]
 * Virtual Address: 0x00198474
 * File Offset:     0x00098474
 * Size (bytes):    372
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global SendUnreliableAll
.type   SendUnreliableAll, %function

SendUnreliableAll:  @ was sub_00198474
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 372 bytes at VA 0x00198474 in build/code.dec.bin
    bx lr
