/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::UserDefinedState::UserDefinedState() [sub_001D3D58]
 * Virtual Address: 0x001D3D58
 * File Offset:     0x000D3D58
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_001D3D58
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x001D3D58 in build/code.dec.bin
    bx lr
