/* DashDecomp — NODECOMPILED stub
 * Function: nn::snd::CTR::FxDelay::Finalize() [sub_002272EC]
 * Virtual Address: 0x002272EC
 * File Offset:     0x001272EC
 * Size (bytes):    92
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002272EC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 92 bytes at VA 0x002272EC in build/code.dec.bin
    bx lr
