/* DashDecomp — NODECOMPILED stub
 * Function: Item::ItemReactProxy::getType() const [sub_00502680]
 * Virtual Address: 0x00502680
 * File Offset:     0x00402680
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00502680
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00502680 in build/code.dec.bin
    bx lr
