/* DashDecomp — NODECOMPILED stub
 * Function: Enemy::IsRaceTypeThinkAsRace() [sub_0033BB34]
 * Virtual Address: 0x0033BB34
 * File Offset:     0x0023BB34
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_0033BB34
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x0033BB34 in build/code.dec.bin
    bx lr
