/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::ConnectionInfo::AddURL(const nn::nex::StationURL&)
 * Virtual Address: 0x0018CD44
 * File Offset:     0x0008CD44
 * Size (bytes):    80
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AddURL
.type   AddURL, %function

AddURL:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 80 bytes at VA 0x0018CD44 in build/code.dec.bin
    bx lr
