/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::Network::RemoveLocalURL(const nn::nex::StationURL&) [sub_00212ABC]
 * Virtual Address: 0x00212ABC
 * File Offset:     0x00112ABC
 * Size (bytes):    292
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00212ABC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 292 bytes at VA 0x00212ABC in build/code.dec.bin
    bx lr
