/* DashDecomp — NODECOMPILED stub
 * Function: Kart::Driver::startGoalMotion(bool) [sub_002F377C]
 * Virtual Address: 0x002F377C
 * File Offset:     0x001F377C
 * Size (bytes):    148
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002F377C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 148 bytes at VA 0x002F377C in build/code.dec.bin
    bx lr
