/* DashDecomp — NODECOMPILED stub
 * Function: Net::NetworkEngine::initNetworkInfo() [sub_0028F6B8]
 * Virtual Address: 0x0028F6B8
 * File Offset:     0x0018F6B8
 * Size (bytes):    320
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_0028F6B8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 320 bytes at VA 0x0028F6B8 in build/code.dec.bin
    bx lr
