/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::Fog::DynamicBuilder::Create(nw::os::IAllocator*) [sub_00253F28]
 * Virtual Address: 0x00253F28
 * File Offset:     0x00153F28
 * Size (bytes):    196
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00253F28
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 196 bytes at VA 0x00253F28 in build/code.dec.bin
    bx lr
