/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectPathFixedPos::ObjectPathFixedPos(Field::ObjectBase*, Util::KDRailBase*) [sub_0039DA64]
 * Virtual Address: 0x0039DA64
 * File Offset:     0x0029DA64
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0039DA64
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x0039DA64 in build/code.dec.bin
    bx lr
