/* DashDecomp — NODECOMPILED stub
 * Function: Item::ItemObjBomhei::stateInitSelfMove() [sub_002C36E4]
 * Virtual Address: 0x002C36E4
 * File Offset:     0x001C36E4
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002C36E4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x002C36E4 in build/code.dec.bin
    bx lr
