/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::internal::NWCopyVec3WithHeader(float*, const float*, unsigned) [sub_00113828]
 * Virtual Address: 0x00113828
 * File Offset:     0x00013828
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

NWCopyVec3WithHeader:  @ was sub_00113828
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x00113828 in build/code.dec.bin
    bx lr
