/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::SceneNode::IsCircularReference(const nw::gfx::SceneNode*) const [sub_004F6F40]
 * Virtual Address: 0x004F6F40
 * File Offset:     0x003F6F40
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004F6F40
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x004F6F40 in build/code.dec.bin
    bx lr
