/* DashDecomp — NODECOMPILED stub
 * Function: Kart::VehicleControlNet::warp(const sead::Vector3<float>&, const sead::Vector3<float>&, float) [sub_002E8920]
 * Virtual Address: 0x002E8920
 * File Offset:     0x001E8920
 * Size (bytes):    372
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_002E8920
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 372 bytes at VA 0x002E8920 in build/code.dec.bin
    bx lr
