/* DashDecomp — NODECOMPILED stub
 * Function: UI::MiiCheckBar::~MiiCheckBar__deallocating()
 * Virtual Address: 0x001355FC
 * File Offset:     0x000355FC
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global MiiCheckBar_deallocating
.type   MiiCheckBar_deallocating, %function

MiiCheckBar_deallocating:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x001355FC in build/code.dec.bin
    bx lr
