/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectScaleCrash::ObjectScaleCrash() [sub_00123F68]
 * Virtual Address: 0x00123F68
 * File Offset:     0x00023F68
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00123F68
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x00123F68 in build/code.dec.bin
    bx lr
