/* DashDecomp — NODECOMPILED stub
 * Function: UI::RaceRankItemControl::onCalc() [sub_0014FD74]
 * Virtual Address: 0x0014FD74
 * File Offset:     0x0004FD74
 * Size (bytes):    240
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global onCalc
.type   onCalc, %function

onCalc:  @ was sub_0014FD74
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 240 bytes at VA 0x0014FD74 in build/code.dec.bin
    bx lr
