/* DashDecomp — NODECOMPILED stub
 * Function: Render::DrawMdl::isStepOver(float) const [sub_004B78FC]
 * Virtual Address: 0x004B78FC
 * File Offset:     0x003B78FC
 * Size (bytes):    396
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global isStepOver
.type   isStepOver, %function

isStepOver:  @ was sub_004B78FC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 396 bytes at VA 0x004B78FC in build/code.dec.bin
    bx lr
