/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::Station::IsConnected() const [sub_0049726C]
 * Virtual Address: 0x0049726C
 * File Offset:     0x0039726C
 * Size (bytes):    196
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global IsConnected
.type   IsConnected, %function

IsConnected:  @ was sub_0049726C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 196 bytes at VA 0x0049726C in build/code.dec.bin
    bx lr
