/* DashDecomp — NODECOMPILED stub
 * Function: nn::applet::CTR::detail::APPLET::PrepareToJumpToHomeMenu() [sub_00207E8C]
 * Virtual Address: 0x00207E8C
 * File Offset:     0x00107E8C
 * Size (bytes):    272
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global PrepareToJumpToHomeMenu
.type   PrepareToJumpToHomeMenu, %function

PrepareToJumpToHomeMenu:  @ was sub_00207E8C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 272 bytes at VA 0x00207E8C in build/code.dec.bin
    bx lr
