/* DashDecomp — NODECOMPILED stub
 * Function: Kart::DriverHop::applyToCurrPrevAnim() [sub_003012A8]
 * Virtual Address: 0x003012A8
 * File Offset:     0x002012A8
 * Size (bytes):    444
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_003012A8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 444 bytes at VA 0x003012A8 in build/code.dec.bin
    bx lr
