/* DashDecomp — NODECOMPILED stub
 * Function: UI::SlotSelect::defineReel_Body() [sub_00130730]
 * Virtual Address: 0x00130730
 * File Offset:     0x00030730
 * Size (bytes):    132
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

defineReel_Body:  @ was sub_00130730
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 132 bytes at VA 0x00130730 in build/code.dec.bin
    bx lr
