/* DashDecomp — NODECOMPILED stub
 * Function: nn::applet::CTR::SetSleepQueryCallback(nn::applet::CTR::QueryReply(*)(unsigned), unsigned)
 * Virtual Address: 0x00100D40
 * File Offset:     0x00000D40
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global nn_applet_CTR_SetSleepQueryCallback
.type   nn_applet_CTR_SetSleepQueryCallback, %function

nn_applet_CTR_SetSleepQueryCallback:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00100D40 in build/code.dec.bin
    bx lr
