/* DashDecomp — NODECOMPILED stub
 * Function: nn::gxlow::CTR::WriteHWRegs(unsigned, const void*, unsigned) [sub_0010EAA0]
 * Virtual Address: 0x0010EAA0
 * File Offset:     0x0000EAA0
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

WriteHWRegs:  @ was sub_0010EAA0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x0010EAA0 in build/code.dec.bin
    bx lr
