/* DashDecomp — NODECOMPILED stub
 * Function: setlocale [sub_00119A94]
 * Virtual Address: 0x00119A94
 * File Offset:     0x00019A94
 * Size (bytes):    188
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00119A94
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 188 bytes at VA 0x00119A94 in build/code.dec.bin
    bx lr
