/* DashDecomp — NODECOMPILED stub
 * Function: sub_00187360
 * Virtual Address: 0x00187360
 * File Offset:     0x00087360
 * Size (bytes):    368
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00187360
.type   sub_00187360, %function

sub_00187360:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 368 bytes at VA 0x00187360 in build/code.dec.bin
    bx lr
