/* DashDecomp — NODECOMPILED stub
 * Function: sub_001124CC
 * Virtual Address: 0x001124CC
 * File Offset:     0x000124CC
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001124CC
.type   sub_001124CC, %function

sub_001124CC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x001124CC in build/code.dec.bin
    bx lr
