/* DashDecomp — NODECOMPILED stub
 * Function: sub_00189220
 * Virtual Address: 0x00189220
 * File Offset:     0x00089220
 * Size (bytes):    80
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00189220
.type   sub_00189220, %function

sub_00189220:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 80 bytes at VA 0x00189220 in build/code.dec.bin
    bx lr
