/* DashDecomp — NODECOMPILED stub
 * Function: sub_00143804
 * Virtual Address: 0x00143804
 * File Offset:     0x00043804
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00143804
.type   sub_00143804, %function

sub_00143804:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x1E, 0x4D, 0x00, 0xEB, 0x10, 0x40, 0xBD, 0xE8, 0x73, 0x8D, 0x0F, 0xEA
