/* DashDecomp — NODECOMPILED stub
 * Function: sub_0015FB44
 * Virtual Address: 0x0015FB44
 * File Offset:     0x0005FB44
 * Size (bytes):    88
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0015FB44
.type   sub_0015FB44, %function

sub_0015FB44:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 88 bytes at VA 0x0015FB44 in build/code.dec.bin
    bx lr
