/* DashDecomp — NODECOMPILED stub
 * Function: sub_0013D400
 * Virtual Address: 0x0013D400
 * File Offset:     0x0003D400
 * Size (bytes):    204
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0013D400
.type   sub_0013D400, %function

sub_0013D400:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 204 bytes at VA 0x0013D400 in build/code.dec.bin
    bx lr
