/* DashDecomp — NODECOMPILED stub
 * Function: sub_00184CD4
 * Virtual Address: 0x00184CD4
 * File Offset:     0x00084CD4
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00184CD4
.type   sub_00184CD4, %function

sub_00184CD4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x00184CD4 in build/code.dec.bin
    bx lr
