/* DashDecomp — NODECOMPILED stub
 * Function: sub_00184950
 * Virtual Address: 0x00184950
 * File Offset:     0x00084950
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00184950
.type   sub_00184950, %function


.section .text
.global sub_00184950
.type   sub_00184950, %function

sub_00184950:
    .byte 0x00, 0x00, 0x50, 0xE3, 0x01, 0x00, 0x00, 0x1A, 0x08, 0x00, 0x9F, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
    .byte 0x00, 0xF0, 0x20, 0xE3, 0x2D, 0x01, 0x00, 0xEA, 0xFF, 0x9F, 0x40, 0xE0
