/* DashDecomp — NODECOMPILED stub
 * Function: sub_00165634
 * Virtual Address: 0x00165634
 * File Offset:     0x00065634
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00165634
.type   sub_00165634, %function

sub_00165634:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00165634 in build/code.dec.bin
    bx lr
