/* DashDecomp — NODECOMPILED stub
 * Function: sub_00142960
 * Virtual Address: 0x00142960
 * File Offset:     0x00042960
 * Size (bytes):    192
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00142960
.type   sub_00142960, %function

sub_00142960:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 192 bytes at VA 0x00142960 in build/code.dec.bin
    bx lr
