/* DashDecomp — NODECOMPILED stub
 * Function: sub_0017C3BC
 * Virtual Address: 0x0017C3BC
 * File Offset:     0x0007C3BC
 * Size (bytes):    1244
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0017C3BC
.type   sub_0017C3BC, %function

sub_0017C3BC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1244 bytes at VA 0x0017C3BC in build/code.dec.bin
    bx lr
