/* DashDecomp — NODECOMPILED stub
 * Function: sub_00106184
 * Virtual Address: 0x00106184
 * File Offset:     0x00006184
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00106184
.type   sub_00106184, %function

sub_00106184:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x00106184 in build/code.dec.bin
    bx lr
