/* DashDecomp — NODECOMPILED stub
 * Function: sub_001C46CC
 * Virtual Address: 0x001C46CC
 * File Offset:     0x000C46CC
 * Size (bytes):    808
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001C46CC
.type   sub_001C46CC, %function

sub_001C46CC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 808 bytes at VA 0x001C46CC in build/code.dec.bin
    bx lr
