/* DashDecomp — NODECOMPILED stub
 * Function: sub_00132E08
 * Virtual Address: 0x00132E08
 * File Offset:     0x00032E08
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00132E08
.type   sub_00132E08, %function

sub_00132E08:
    .byte 0x00, 0x00, 0xD0, 0xE5, 0x20, 0x00, 0x00, 0xE2, 0xA0, 0x02, 0xA0, 0xE1, 0x1E, 0xFF, 0x2F, 0xE1
