/* DashDecomp — NODECOMPILED stub
 * Function: sub_001A48EC
 * Virtual Address: 0x001A48EC
 * File Offset:     0x000A48EC
 * Size (bytes):    340
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001A48EC
.type   sub_001A48EC, %function

sub_001A48EC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 340 bytes at VA 0x001A48EC in build/code.dec.bin
    bx lr
