/* DashDecomp — NODECOMPILED stub
 * Function: sub_001208F0
 * Virtual Address: 0x001208F0
 * File Offset:     0x000208F0
 * Size (bytes):    252
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001208F0
.type   sub_001208F0, %function

sub_001208F0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 252 bytes at VA 0x001208F0 in build/code.dec.bin
    bx lr
