/* DashDecomp — NODECOMPILED stub
 * Function: sub_00193A90
 * Virtual Address: 0x00193A90
 * File Offset:     0x00093A90
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00193A90
.type   sub_00193A90, %function

sub_00193A90:
    .byte 0x04, 0x00, 0x50, 0xE3, 0x01, 0x00, 0x00, 0x3A, 0x0C, 0x00, 0x9F, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
    .byte 0x01, 0x10, 0xA0, 0xE3, 0x11, 0x00, 0xA0, 0xE1, 0xCD, 0xBE, 0xFD, 0xEA
