/* DashDecomp — NODECOMPILED stub
 * Function: sub_00171960
 * Virtual Address: 0x00171960
 * File Offset:     0x00071960
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00171960
.type   sub_00171960, %function

sub_00171960:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x00171960 in build/code.dec.bin
    bx lr
