/* DashDecomp — NODECOMPILED stub
 * Function: sub_00144388
 * Virtual Address: 0x00144388
 * File Offset:     0x00044388
 * Size (bytes):    568
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00144388
.type   sub_00144388, %function

sub_00144388:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 568 bytes at VA 0x00144388 in build/code.dec.bin
    bx lr
