/* DashDecomp — NODECOMPILED stub
 * Function: sub_001CF778
 * Virtual Address: 0x001CF778
 * File Offset:     0x000CF778
 * Size (bytes):    328
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001CF778
.type   sub_001CF778, %function

sub_001CF778:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 328 bytes at VA 0x001CF778 in build/code.dec.bin
    bx lr
