/* DashDecomp — NODECOMPILED stub
 * Function: sub_0015CE6C
 * Virtual Address: 0x0015CE6C
 * File Offset:     0x0005CE6C
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0015CE6C
.type   sub_0015CE6C, %function

sub_0015CE6C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x0015CE6C in build/code.dec.bin
    bx lr
