/* DashDecomp — NODECOMPILED stub
 * Function: sub_0014BC84
 * Virtual Address: 0x0014BC84
 * File Offset:     0x0004BC84
 * Size (bytes):    192
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0014BC84
.type   sub_0014BC84, %function

sub_0014BC84:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 192 bytes at VA 0x0014BC84 in build/code.dec.bin
    bx lr
