/* DashDecomp — NODECOMPILED stub
 * Function: sub_001B62BC
 * Virtual Address: 0x001B62BC
 * File Offset:     0x000B62BC
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001B62BC
.type   sub_001B62BC, %function

sub_001B62BC:
    .byte 0x04, 0x10, 0x9F, 0xE5, 0x00, 0x10, 0x80, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
