/* DashDecomp — NODECOMPILED stub
 * Function: sub_00123C34
 * Virtual Address: 0x00123C34
 * File Offset:     0x00023C34
 * Size (bytes):    216
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00123C34
.type   sub_00123C34, %function

sub_00123C34:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 216 bytes at VA 0x00123C34 in build/code.dec.bin
    bx lr
