/* DashDecomp — NODECOMPILED stub
 * Function: sub_00105C0C
 * Virtual Address: 0x00105C0C
 * File Offset:     0x00005C0C
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00105C0C
.type   sub_00105C0C, %function

sub_00105C0C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x00105C0C in build/code.dec.bin
    bx lr
