/* DashDecomp — NODECOMPILED stub
 * Function: sub_00177424
 * Virtual Address: 0x00177424
 * File Offset:     0x00077424
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00177424
.type   sub_00177424, %function

sub_00177424:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x00177424 in build/code.dec.bin
    bx lr
