/* DashDecomp — NODECOMPILED stub
 * Function: sub_00138970
 * Virtual Address: 0x00138970
 * File Offset:     0x00038970
 * Size (bytes):    248
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00138970
.type   sub_00138970, %function

sub_00138970:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 248 bytes at VA 0x00138970 in build/code.dec.bin
    bx lr
