/* DashDecomp — NODECOMPILED stub
 * Function: sub_0010C3E4
 * Virtual Address: 0x0010C3E4
 * File Offset:     0x0000C3E4
 * Size (bytes):    232
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0010C3E4
.type   sub_0010C3E4, %function

sub_0010C3E4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 232 bytes at VA 0x0010C3E4 in build/code.dec.bin
    bx lr
