/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018D2F4
 * Virtual Address: 0x0018D2F4
 * File Offset:     0x0008D2F4
 * Size (bytes):    112
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018D2F4
.type   sub_0018D2F4, %function

sub_0018D2F4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 112 bytes at VA 0x0018D2F4 in build/code.dec.bin
    bx lr
