/* DashDecomp — NODECOMPILED stub
 * Function: sub_0014FA70
 * Virtual Address: 0x0014FA70
 * File Offset:     0x0004FA70
 * Size (bytes):    344
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0014FA70
.type   sub_0014FA70, %function

sub_0014FA70:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 344 bytes at VA 0x0014FA70 in build/code.dec.bin
    bx lr
