/* DashDecomp — NODECOMPILED stub
 * Function: sub_001C90A0
 * Virtual Address: 0x001C90A0
 * File Offset:     0x000C90A0
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001C90A0
.type   sub_001C90A0, %function

sub_001C90A0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x001C90A0 in build/code.dec.bin
    bx lr
