/* DashDecomp — NODECOMPILED stub
 * Function: sub_00106240
 * Virtual Address: 0x00106240
 * File Offset:     0x00006240
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00106240
.type   sub_00106240, %function

sub_00106240:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x00106240 in build/code.dec.bin
    bx lr
