/* DashDecomp — NODECOMPILED stub
 * Function: sub_001D2E60
 * Virtual Address: 0x001D2E60
 * File Offset:     0x000D2E60
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001D2E60
.type   sub_001D2E60, %function

sub_001D2E60:
    .byte 0x04, 0x10, 0x9F, 0xE5, 0x00, 0x10, 0x80, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
