/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018FC58
 * Virtual Address: 0x0018FC58
 * File Offset:     0x0008FC58
 * Size (bytes):    92
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018FC58
.type   sub_0018FC58, %function

sub_0018FC58:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 92 bytes at VA 0x0018FC58 in build/code.dec.bin
    bx lr
