/* DashDecomp — NODECOMPILED stub
 * Function: sub_0014E49C
 * Virtual Address: 0x0014E49C
 * File Offset:     0x0004E49C
 * Size (bytes):    284
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0014E49C
.type   sub_0014E49C, %function

sub_0014E49C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 284 bytes at VA 0x0014E49C in build/code.dec.bin
    bx lr
