/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018E89C
 * Virtual Address: 0x0018E89C
 * File Offset:     0x0008E89C
 * Size (bytes):    88
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018E89C
.type   sub_0018E89C, %function

sub_0018E89C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 88 bytes at VA 0x0018E89C in build/code.dec.bin
    bx lr
