/* DashDecomp — NODECOMPILED stub
 * Function: sub_0010DBCC
 * Virtual Address: 0x0010DBCC
 * File Offset:     0x0000DBCC
 * Size (bytes):    356
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0010DBCC
.type   sub_0010DBCC, %function

sub_0010DBCC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 356 bytes at VA 0x0010DBCC in build/code.dec.bin
    bx lr
