/* DashDecomp — NODECOMPILED stub
 * Function: sub_00182BD8
 * Virtual Address: 0x00182BD8
 * File Offset:     0x00082BD8
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00182BD8
.type   sub_00182BD8, %function

sub_00182BD8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x00182BD8 in build/code.dec.bin
    bx lr
