/* DashDecomp — NODECOMPILED stub
 * Function: sub_0017EAF0
 * Virtual Address: 0x0017EAF0
 * File Offset:     0x0007EAF0
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0017EAF0
.type   sub_0017EAF0, %function

sub_0017EAF0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x0017EAF0 in build/code.dec.bin
    bx lr
