/* DashDecomp — NODECOMPILED stub
 * Function: sub_0011D968
 * Virtual Address: 0x0011D968
 * File Offset:     0x0001D968
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0011D968
.type   sub_0011D968, %function

sub_0011D968:
    .byte 0xB2, 0xA0, 0xD1, 0xE0, 0x10, 0x20, 0x82, 0xE2, 0x10, 0x90, 0x62, 0xE2, 0x1A, 0x39, 0x83, 0xE1
    .byte 0x0E, 0xF0, 0xA0, 0xE1
