/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018CDC0
 * Virtual Address: 0x0018CDC0
 * File Offset:     0x0008CDC0
 * Size (bytes):    316
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018CDC0
.type   sub_0018CDC0, %function

sub_0018CDC0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 316 bytes at VA 0x0018CDC0 in build/code.dec.bin
    bx lr
