/* DashDecomp — NODECOMPILED stub
 * Function: sub_0010BB20
 * Virtual Address: 0x0010BB20
 * File Offset:     0x0000BB20
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0010BB20
.type   sub_0010BB20, %function

sub_0010BB20:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x0010BB20 in build/code.dec.bin
    bx lr
