/* DashDecomp — NODECOMPILED stub
 * Function: sub_001831EC
 * Virtual Address: 0x001831EC
 * File Offset:     0x000831EC
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001831EC
.type   sub_001831EC, %function

sub_001831EC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x001831EC in build/code.dec.bin
    bx lr
