/* DashDecomp — NODECOMPILED stub
 * Function: sub_00132C74
 * Virtual Address: 0x00132C74
 * File Offset:     0x00032C74
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00132C74
.type   sub_00132C74, %function

sub_00132C74:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00132C74 in build/code.dec.bin
    bx lr
