/* DashDecomp — NODECOMPILED stub
 * Function: sub_0062FA7C
 * Virtual Address: 0x0062FA7C
 * File Offset:     0x0052FA7C
 * Size (bytes):    308
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_0062FA7C
.type   sub_0062FA7C, %function

sub_0062FA7C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 308 bytes at VA 0x0062FA7C in build/code.dec.bin
    bx lr
