/* DashDecomp — NODECOMPILED stub
 * Function: sub_0014B534
 * Virtual Address: 0x0014B534
 * File Offset:     0x0004B534
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0014B534
.type   sub_0014B534, %function

sub_0014B534:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x0014B534 in build/code.dec.bin
    bx lr
