/* DashDecomp — NODECOMPILED stub
 * Function: sub_0019BACC
 * Virtual Address: 0x0019BACC
 * File Offset:     0x0009BACC
 * Size (bytes):    104
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0019BACC
.type   sub_0019BACC, %function

sub_0019BACC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 104 bytes at VA 0x0019BACC in build/code.dec.bin
    bx lr
