/* DashDecomp — NODECOMPILED stub
 * Function: sub_00190598
 * Virtual Address: 0x00190598
 * File Offset:     0x00090598
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00190598
.type   sub_00190598, %function

sub_00190598:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x00190598 in build/code.dec.bin
    bx lr
