/* DashDecomp — NODECOMPILED stub
 * Function: sub_00155D64
 * Virtual Address: 0x00155D64
 * File Offset:     0x00055D64
 * Size (bytes):    268
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00155D64
.type   sub_00155D64, %function

sub_00155D64:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 268 bytes at VA 0x00155D64 in build/code.dec.bin
    bx lr
