/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018E72C
 * Virtual Address: 0x0018E72C
 * File Offset:     0x0008E72C
 * Size (bytes):    188
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018E72C
.type   sub_0018E72C, %function

sub_0018E72C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 188 bytes at VA 0x0018E72C in build/code.dec.bin
    bx lr
