/* DashDecomp — NODECOMPILED stub
 * Function: sub_001CB778
 * Virtual Address: 0x001CB778
 * File Offset:     0x000CB778
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001CB778
.type   sub_001CB778, %function

sub_001CB778:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x001CB778 in build/code.dec.bin
    bx lr
