/* DashDecomp — NODECOMPILED stub
 * Function: sub_001CD630
 * Virtual Address: 0x001CD630
 * File Offset:     0x000CD630
 * Size (bytes):    168
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001CD630
.type   sub_001CD630, %function

sub_001CD630:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 168 bytes at VA 0x001CD630 in build/code.dec.bin
    bx lr
