/* DashDecomp — NODECOMPILED stub
 * Function: sub_00139B00
 * Virtual Address: 0x00139B00
 * File Offset:     0x00039B00
 * Size (bytes):    188
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00139B00
.type   sub_00139B00, %function

sub_00139B00:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 188 bytes at VA 0x00139B00 in build/code.dec.bin
    bx lr
