/* DashDecomp — NODECOMPILED stub
 * Function: sub_00186B7C
 * Virtual Address: 0x00186B7C
 * File Offset:     0x00086B7C
 * Size (bytes):    188
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00186B7C
.type   sub_00186B7C, %function

sub_00186B7C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 188 bytes at VA 0x00186B7C in build/code.dec.bin
    bx lr
