/* DashDecomp — NODECOMPILED stub
 * Function: sub_00187078
 * Virtual Address: 0x00187078
 * File Offset:     0x00087078
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00187078
.type   sub_00187078, %function

sub_00187078:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x00187078 in build/code.dec.bin
    bx lr
