/* DashDecomp — NODECOMPILED stub
 * Function: sub_001940A4
 * Virtual Address: 0x001940A4
 * File Offset:     0x000940A4
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001940A4
.type   sub_001940A4, %function

sub_001940A4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x001940A4 in build/code.dec.bin
    bx lr
