/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018BBA8
 * Virtual Address: 0x0018BBA8
 * File Offset:     0x0008BBA8
 * Size (bytes):    188
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018BBA8
.type   sub_0018BBA8, %function

sub_0018BBA8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 188 bytes at VA 0x0018BBA8 in build/code.dec.bin
    bx lr
