/* DashDecomp — NODECOMPILED stub
 * Function: sub_00175F04
 * Virtual Address: 0x00175F04
 * File Offset:     0x00075F04
 * Size (bytes):    240
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00175F04
.type   sub_00175F04, %function

sub_00175F04:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 240 bytes at VA 0x00175F04 in build/code.dec.bin
    bx lr
