/* DashDecomp — NODECOMPILED stub
 * Function: sub_001114B0
 * Virtual Address: 0x001114B0
 * File Offset:     0x000114B0
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001114B0
.type   sub_001114B0, %function

sub_001114B0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x001114B0 in build/code.dec.bin
    bx lr
