/* DashDecomp — NODECOMPILED stub
 * Function: sub_0014CDBC
 * Virtual Address: 0x0014CDBC
 * File Offset:     0x0004CDBC
 * Size (bytes):    264
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0014CDBC
.type   sub_0014CDBC, %function

sub_0014CDBC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 264 bytes at VA 0x0014CDBC in build/code.dec.bin
    bx lr
