/* DashDecomp — NODECOMPILED stub
 * Function: sub_00194B70
 * Virtual Address: 0x00194B70
 * File Offset:     0x00094B70
 * Size (bytes):    404
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00194B70
.type   sub_00194B70, %function

sub_00194B70:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 404 bytes at VA 0x00194B70 in build/code.dec.bin
    bx lr
