/* DashDecomp — NODECOMPILED stub
 * Function: sub_00110B9C
 * Virtual Address: 0x00110B9C
 * File Offset:     0x00010B9C
 * Size (bytes):    268
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00110B9C
.type   sub_00110B9C, %function

sub_00110B9C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 268 bytes at VA 0x00110B9C in build/code.dec.bin
    bx lr
