/* DashDecomp — NODECOMPILED stub
 * Function: sub_0019F9D8
 * Virtual Address: 0x0019F9D8
 * File Offset:     0x0009F9D8
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0019F9D8
.type   sub_0019F9D8, %function

sub_0019F9D8:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x17, 0x5B, 0x00, 0xEB, 0x0C, 0x00, 0x80, 0xE2, 0x10, 0x80, 0xBD, 0xE8
