/* DashDecomp — NODECOMPILED stub
 * Function: sub_00112508
 * Virtual Address: 0x00112508
 * File Offset:     0x00012508
 * Size (bytes):    64
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00112508
.type   sub_00112508, %function

sub_00112508:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 64 bytes at VA 0x00112508 in build/code.dec.bin
    bx lr
