/* DashDecomp — NODECOMPILED stub
 * Function: sub_001550FC
 * Virtual Address: 0x001550FC
 * File Offset:     0x000550FC
 * Size (bytes):    256
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001550FC
.type   sub_001550FC, %function

sub_001550FC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 256 bytes at VA 0x001550FC in build/code.dec.bin
    bx lr
