/* DashDecomp — NODECOMPILED stub
 * Function: sub_0019D024
 * Virtual Address: 0x0019D024
 * File Offset:     0x0009D024
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0019D024
.type   sub_0019D024, %function

sub_0019D024:
    .byte 0xB8, 0x10, 0xD0, 0xE1, 0x00, 0x00, 0x51, 0xE3, 0x1E, 0x00, 0xD0, 0x15, 0x01, 0x00, 0x50, 0x13
    .byte 0x00, 0x00, 0xA0, 0x93, 0x01, 0x00, 0xA0, 0x83, 0x1E, 0xFF, 0x2F, 0xE1
