/* DashDecomp — NODECOMPILED stub
 * Function: sub_001845BC
 * Virtual Address: 0x001845BC
 * File Offset:     0x000845BC
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001845BC
.type   sub_001845BC, %function

sub_001845BC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x001845BC in build/code.dec.bin
    bx lr
