/* DashDecomp — NODECOMPILED stub
 * Function: sub_00184A2C
 * Virtual Address: 0x00184A2C
 * File Offset:     0x00084A2C
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00184A2C
.type   sub_00184A2C, %function


.section .text
.global sub_00184A2C
.type   sub_00184A2C, %function

sub_00184A2C:
    .byte 0x00, 0x00, 0x50, 0xE3, 0x00, 0x00, 0x90, 0x15, 0x00, 0x00, 0x50, 0x13, 0x2A, 0x01, 0x00, 0x1A
    .byte 0x00, 0x00, 0x9F, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1, 0xFF, 0x9F, 0x40, 0xE0
