/* DashDecomp — NODECOMPILED stub
 * Function: sub_0019470C
 * Virtual Address: 0x0019470C
 * File Offset:     0x0009470C
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0019470C
.type   sub_0019470C, %function

sub_0019470C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x0019470C in build/code.dec.bin
    bx lr
