/* DashDecomp — NODECOMPILED stub
 * Function: sub_001AF102
 * Virtual Address: 0x001AF102
 * File Offset:     0x000AF102
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_001AF102
.type   sub_001AF102, %function

sub_001AF102:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x001AF102 in build/code.dec.bin
    bx lr
