/* DashDecomp — NODECOMPILED stub
 * Function: sub_0011CFE4
 * Virtual Address: 0x0011CFE4
 * File Offset:     0x0001CFE4
 * Size (bytes):    480
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0011CFE4
.type   sub_0011CFE4, %function

sub_0011CFE4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 480 bytes at VA 0x0011CFE4 in build/code.dec.bin
    bx lr
