/* DashDecomp — NODECOMPILED stub
 * Function: sub_001179DE
 * Virtual Address: 0x001179DE
 * File Offset:     0x000179DE
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_001179DE
.type   sub_001179DE, %function

sub_001179DE:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x001179DE in build/code.dec.bin
    bx lr
