/* DashDecomp — NODECOMPILED stub
 * Function: sub_0014B570
 * Virtual Address: 0x0014B570
 * File Offset:     0x0004B570
 * Size (bytes):    184
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0014B570
.type   sub_0014B570, %function

sub_0014B570:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 184 bytes at VA 0x0014B570 in build/code.dec.bin
    bx lr
