/* DashDecomp — NODECOMPILED stub
 * Function: sub_001C4AC4
 * Virtual Address: 0x001C4AC4
 * File Offset:     0x000C4AC4
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001C4AC4
.type   sub_001C4AC4, %function

sub_001C4AC4:
    .byte 0xB0, 0x23, 0x90, 0xE5, 0x01, 0x00, 0x52, 0xE1, 0x02, 0x10, 0xA0, 0x21, 0xB0, 0x13, 0x80, 0xE5
    .byte 0x1E, 0xFF, 0x2F, 0xE1
