/* DashDecomp — NODECOMPILED stub
 * Function: sub_0018F314
 * Virtual Address: 0x0018F314
 * File Offset:     0x0008F314
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0018F314
.type   sub_0018F314, %function

sub_0018F314:
    .byte 0x80, 0x02, 0x60, 0xE0, 0xDB, 0x3D, 0xA0, 0xE3, 0x80, 0x00, 0x80, 0xE0, 0x00, 0x32, 0x83, 0xE0
    .byte 0x00, 0x02, 0x83, 0xE0, 0x92, 0x01, 0x20, 0xE0, 0x1E, 0xFF, 0x2F, 0xE1
