/* DashDecomp — NODECOMPILED stub
 * Function: sub_001D36C0
 * Virtual Address: 0x001D36C0
 * File Offset:     0x000D36C0
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001D36C0
.type   sub_001D36C0, %function

sub_001D36C0:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x04, 0x10, 0x91, 0xE5, 0x48, 0x00, 0x80, 0xE2, 0x6B, 0x16, 0xFF, 0xEB
    .byte 0x01, 0x00, 0xA0, 0xE3, 0x10, 0x80, 0xBD, 0xE8
