/* DashDecomp — NODECOMPILED stub
 * Function: sub_00165B14
 * Virtual Address: 0x00165B14
 * File Offset:     0x00065B14
 * Size (bytes):    160
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00165B14
.type   sub_00165B14, %function

sub_00165B14:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 160 bytes at VA 0x00165B14 in build/code.dec.bin
    bx lr
