/* DashDecomp — NODECOMPILED stub
 * Function: sub_00132C64
 * Virtual Address: 0x00132C64
 * File Offset:     0x00032C64
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00132C64
.type   sub_00132C64, %function

sub_00132C64:
    .byte 0x04, 0x00, 0x9F, 0xE5, 0x01, 0x00, 0xD0, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
