/* DashDecomp — NODECOMPILED stub
 * Function: sub_00102E28
 * Virtual Address: 0x00102E28
 * File Offset:     0x00002E28
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00102E28
.type   sub_00102E28, %function

sub_00102E28:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x00102E28 in build/code.dec.bin
    bx lr
