/* DashDecomp — NODECOMPILED stub
 * Function: sub_0019AAD0
 * Virtual Address: 0x0019AAD0
 * File Offset:     0x0009AAD0
 * Size (bytes):    368
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0019AAD0
.type   sub_0019AAD0, %function

sub_0019AAD0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 368 bytes at VA 0x0019AAD0 in build/code.dec.bin
    bx lr
