/* DashDecomp — NODECOMPILED stub
 * Function: sub_0016FFEC
 * Virtual Address: 0x0016FFEC
 * File Offset:     0x0006FFEC
 * Size (bytes):    88
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0016FFEC
.type   sub_0016FFEC, %function

sub_0016FFEC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 88 bytes at VA 0x0016FFEC in build/code.dec.bin
    bx lr
