/* DashDecomp — NODECOMPILED stub
 * Function: sub_001C80A0
 * Virtual Address: 0x001C80A0
 * File Offset:     0x000C80A0
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001C80A0
.type   sub_001C80A0, %function

sub_001C80A0:
    .byte 0xA2, 0xAE, 0xFF, 0xEA
