/* DashDecomp — NODECOMPILED stub
 * Function: sub_00615A74
 * Virtual Address: 0x00615A74
 * File Offset:     0x00515A74
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_00615A74
.type   sub_00615A74, %function

sub_00615A74:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x00615A74 in build/code.dec.bin
    bx lr
