/* DashDecomp — NODECOMPILED stub
 * Function: sub_00104340
 * Virtual Address: 0x00104340
 * File Offset:     0x00004340
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00104340
.type   sub_00104340, %function

sub_00104340:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x00104340 in build/code.dec.bin
    bx lr
