/* DashDecomp — NODECOMPILED stub
 * Function: sub_001835AC
 * Virtual Address: 0x001835AC
 * File Offset:     0x000835AC
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001835AC
.type   sub_001835AC, %function

sub_001835AC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x001835AC in build/code.dec.bin
    bx lr
