/* DashDecomp — NODECOMPILED stub
 * Function: sub_001146C0
 * Virtual Address: 0x001146C0
 * File Offset:     0x000146C0
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001146C0
.type   sub_001146C0, %function

sub_001146C0:
    .byte 0x0C, 0x0A, 0xB1, 0xEC, 0x04, 0x6A, 0x92, 0xEC, 0x10, 0x0A, 0x80, 0xEC, 0x1E, 0xFF, 0x2F, 0xE1
