/* DashDecomp — NODECOMPILED stub
 * Function: sub_00178244
 * Virtual Address: 0x00178244
 * File Offset:     0x00078244
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00178244
.type   sub_00178244, %function

sub_00178244:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x00178244 in build/code.dec.bin
    bx lr
