/* DashDecomp — NODECOMPILED stub
 * Function: UI::ControlInitializer::initCreateArg(UI::Control::CreateArg*)
 * Virtual Address: 0x0014C044
 * File Offset:     0x0004C044
 * Size (bytes):    428
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global UI_ControlInitializer_initCreateArg
.type   UI_ControlInitializer_initCreateArg, %function

UI_ControlInitializer_initCreateArg:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 428 bytes at VA 0x0014C044 in build/code.dec.bin
    bx lr
