/* DashDecomp — NODECOMPILED stub
 * Function: UI::MchChCursor::setPosition(const sead::Vector3<float>&) [sub_00159D58]
 * Virtual Address: 0x00159D58
 * File Offset:     0x00059D58
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00159D58
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x00159D58 in build/code.dec.bin
    bx lr
