/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::MenuMulti_Group::procOpenMenu() [sub_001674B4]
 * Virtual Address: 0x001674B4
 * File Offset:     0x000674B4
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_001674B4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x001674B4 in build/code.dec.bin
    bx lr
