/* DashDecomp — NODECOMPILED stub
 * Function: thunk{-164} to System::BackgroundLoadThread::~BackgroundLoadThread() [sub_004CAF00]
 * Virtual Address: 0x004CAF00
 * File Offset:     0x003CAF00
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global BackgroundLoadThread
.type   BackgroundLoadThread, %function

BackgroundLoadThread:  @ was sub_004CAF00
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x004CAF00 in build/code.dec.bin
    bx lr
