/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::internal::BankFile::FileHeader::GetInfoBlock() const [sub_004A2924]
 * Virtual Address: 0x004A2924
 * File Offset:     0x003A2924
 * Size (bytes):    1936
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global GetInfoBlock
.type   GetInfoBlock, %function

GetInfoBlock:  @ was sub_004A2924
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1936 bytes at VA 0x004A2924 in build/code.dec.bin
    bx lr
