/* DashDecomp — NODECOMPILED stub
 * Function: Kart::DispWing::replaceVariationTexture_(nw::gfx::res::ResGraphicsFile, nw::gfx::res::ResModel, int, int, bool) const [sub_00504620]
 * Virtual Address: 0x00504620
 * File Offset:     0x00404620
 * Size (bytes):    536
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00504620
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 536 bytes at VA 0x00504620 in build/code.dec.bin
    bx lr
