/* DashDecomp — NODECOMPILED stub
 * Function: sead::ptcl::EmitterCalc::_emitSphereSameDivide(sead::ptcl::EmitterInstance*) [sub_00319FE4]
 * Virtual Address: 0x00319FE4
 * File Offset:     0x00219FE4
 * Size (bytes):    236
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00319FE4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 236 bytes at VA 0x00319FE4 in build/code.dec.bin
    bx lr
