/* DashDecomp — NODECOMPILED stub
 * Function: Effect::CamEnvParticleRain::Draw(unsigned*, nn::math::VEC4&, float, const nn::math::MTX34&, nn::math::VEC3*, nn::math::VEC4*, float*, nn::math::VEC3&, nn::math::VEC4&, nn::math::VEC4&, nn::math::VEC4&, const nn::math::VEC3&, int, const nn::math::VEC3&, float, float) [sub_003C12D0]
 * Virtual Address: 0x003C12D0
 * File Offset:     0x002C12D0
 * Size (bytes):    896
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Draw
.type   Draw, %function

Draw:  @ was sub_003C12D0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 896 bytes at VA 0x003C12D0 in build/code.dec.bin
    bx lr
