/* DashDecomp — NODECOMPILED stub
 * Function: UI::BaseMenuInputControl::mod(int) const [sub_004E5A54]
 * Virtual Address: 0x004E5A54
 * File Offset:     0x003E5A54
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004E5A54
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x004E5A54 in build/code.dec.bin
    bx lr
