/* DashDecomp — NODECOMPILED stub
 * Function: sead::DoubleCmdGameFrameworkCtrNw4c::procFrame_() [sub_002E4A38]
 * Virtual Address: 0x002E4A38
 * File Offset:     0x001E4A38
 * Size (bytes):    452
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

procFrame:  @ was sub_002E4A38
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 452 bytes at VA 0x002E4A38 in build/code.dec.bin
    bx lr
