/* DashDecomp — NODECOMPILED stub
 * Function: Kart::VehicleControl::changeToCPU(bool) [sub_002B54D8]
 * Virtual Address: 0x002B54D8
 * File Offset:     0x001B54D8
 * Size (bytes):    184
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global changeToCPU
.type   changeToCPU, %function

changeToCPU:  @ was sub_002B54D8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 184 bytes at VA 0x002B54D8 in build/code.dec.bin
    bx lr
