/* DashDecomp — NODECOMPILED stub
 * Function: sead::SoundHandle::isAttachedSound() const [sub_00504924]
 * Virtual Address: 0x00504924
 * File Offset:     0x00404924
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00504924
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00504924 in build/code.dec.bin
    bx lr
