/* DashDecomp — NODECOMPILED stub
 * Function: nn::friends::CTR::detail::Friends::DecryptApproachContext(nn::friends::CTR::ApproachContextPlain*, const nnfriendsApproachContext&, bool, bool) [sub_0023A29C]
 * Virtual Address: 0x0023A29C
 * File Offset:     0x0013A29C
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0023A29C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x0023A29C in build/code.dec.bin
    bx lr
