/* DashDecomp — NODECOMPILED stub
 * Function: nw::ut::LinkList<nw::lyt::internal::Stopwatch, (long)0>::~LinkList() [sub_0023B06C]
 * Virtual Address: 0x0023B06C
 * File Offset:     0x0013B06C
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0023B06C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x0023B06C in build/code.dec.bin
    bx lr
