/* DashDecomp — NODECOMPILED stub
 * Function: sead::ProcessMeterBarBase::getLastTotalSpan() const [sub_00505274]
 * Virtual Address: 0x00505274
 * File Offset:     0x00405274
 * Size (bytes):    200
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00505274
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 200 bytes at VA 0x00505274 in build/code.dec.bin
    bx lr
