/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectSimpleModelBase::calcVisibility() [sub_003AA274]
 * Virtual Address: 0x003AA274
 * File Offset:     0x002AA274
 * Size (bytes):    164
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_003AA274
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 164 bytes at VA 0x003AA274 in build/code.dec.bin
    bx lr
