/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::qList<nn::nex::StationURL>::qList() [sub_0020DC64]
 * Virtual Address: 0x0020DC64
 * File Offset:     0x0010DC64
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_0020DC64
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x0020DC64 in build/code.dec.bin
    bx lr
