/* DashDecomp — NODECOMPILED stub
 * Function: sub_0015A360
 * Virtual Address: 0x0015A360
 * File Offset:     0x0005A360
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0015A360
.type   sub_0015A360, %function

sub_0015A360:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x0015A360 in build/code.dec.bin
    bx lr
