/* DashDecomp — NODECOMPILED stub
 * Function: nw::lyt::Pane::MakeUniformData(nw::lyt::DrawInfo*, nw::lyt::Drawer*) const [sub_0049DBDC]
 * Virtual Address: 0x0049DBDC
 * File Offset:     0x0039DBDC
 * Size (bytes):    340
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global MakeUniformData
.type   MakeUniformData, %function

MakeUniformData:  @ was sub_0049DBDC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 340 bytes at VA 0x0049DBDC in build/code.dec.bin
    bx lr
