/* DashDecomp — NODECOMPILED stub
 * Function: UI::BaseMenuButtonControl::touchHandlerDown(int, const sead::Vector2<float>&) [sub_001701FC]
 * Virtual Address: 0x001701FC
 * File Offset:     0x000701FC
 * Size (bytes):    184
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_001701FC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 184 bytes at VA 0x001701FC in build/code.dec.bin
    bx lr
