/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::internal::driver::SequenceTrack::SetSilence(bool, int) [sub_0024BD10]
 * Virtual Address: 0x0024BD10
 * File Offset:     0x0014BD10
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global SetSilence
.type   SetSilence, %function

SetSilence:  @ was sub_0024BD10
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x0024BD10 in build/code.dec.bin
    bx lr
