/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::_DO_RootDO::SpecificUpdate(nn::nex::DataSet*, const nn::nex::Time&) [sub_00197110]
 * Virtual Address: 0x00197110
 * File Offset:     0x00097110
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00197110
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x00197110 in build/code.dec.bin
    bx lr
