/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020D5BC
 * Virtual Address: 0x0020D5BC
 * File Offset:     0x0010D5BC
 * Size (bytes):    88
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020D5BC
.type   sub_0020D5BC, %function

sub_0020D5BC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 88 bytes at VA 0x0020D5BC in build/code.dec.bin
    bx lr
