/* DashDecomp — NODECOMPILED stub
 * Function: sub_001FCF1C
 * Virtual Address: 0x001FCF1C
 * File Offset:     0x000FCF1C
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001FCF1C
.type   sub_001FCF1C, %function

sub_001FCF1C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x001FCF1C in build/code.dec.bin
    bx lr
