/* DashDecomp — NODECOMPILED stub
 * Function: sub_0026B370
 * Virtual Address: 0x0026B370
 * File Offset:     0x0016B370
 * Size (bytes):    152
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0026B370
.type   sub_0026B370, %function

sub_0026B370:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 152 bytes at VA 0x0026B370 in build/code.dec.bin
    bx lr
