/* DashDecomp — NODECOMPILED stub
 * Function: sub_00276970
 * Virtual Address: 0x00276970
 * File Offset:     0x00176970
 * Size (bytes):    8
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00276970
.type   sub_00276970, %function

sub_00276970:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 8 bytes at VA 0x00276970 in build/code.dec.bin
    bx lr
