/* DashDecomp — NODECOMPILED stub
 * Function: sub_0022E880
 * Virtual Address: 0x0022E880
 * File Offset:     0x0012E880
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0022E880
.type   sub_0022E880, %function

sub_0022E880:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x0022E880 in build/code.dec.bin
    bx lr
