/* DashDecomp — NODECOMPILED stub
 * Function: sub_001F5784
 * Virtual Address: 0x001F5784
 * File Offset:     0x000F5784
 * Size (bytes):    604
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001F5784
.type   sub_001F5784, %function

sub_001F5784:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 604 bytes at VA 0x001F5784 in build/code.dec.bin
    bx lr
