/* DashDecomp — NODECOMPILED stub
 * Function: sub_0027BC44
 * Virtual Address: 0x0027BC44
 * File Offset:     0x0017BC44
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0027BC44
.type   sub_0027BC44, %function

sub_0027BC44:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x0027BC44 in build/code.dec.bin
    bx lr
