/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020E654
 * Virtual Address: 0x0020E654
 * File Offset:     0x0010E654
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020E654
.type   sub_0020E654, %function

sub_0020E654:
    .byte 0x04, 0x10, 0x9F, 0xE5, 0x00, 0x00, 0x81, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
