/* DashDecomp — NODECOMPILED stub
 * Function: sub_0021B14C
 * Virtual Address: 0x0021B14C
 * File Offset:     0x0011B14C
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0021B14C
.type   sub_0021B14C, %function

sub_0021B14C:
    .byte 0x80, 0x10, 0x90, 0xE5, 0x01, 0x10, 0x41, 0xE2, 0x80, 0x10, 0x80, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
