/* DashDecomp — NODECOMPILED stub
 * Function: sub_0023CA6E
 * Virtual Address: 0x0023CA6E
 * File Offset:     0x0013CA6E
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_0023CA6E
.type   sub_0023CA6E, %function

sub_0023CA6E:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 4 bytes at VA 0x0023CA6E in build/code.dec.bin
    bx lr
