/* DashDecomp — NODECOMPILED stub
 * Function: sub_00216A44
 * Virtual Address: 0x00216A44
 * File Offset:     0x00116A44
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00216A44
.type   sub_00216A44, %function

sub_00216A44:
    .byte 0x0C, 0x10, 0x9F, 0xE5, 0x08, 0x20, 0x91, 0xE5, 0x08, 0x00, 0x81, 0xE5, 0x02, 0x00, 0xA0, 0xE1
    .byte 0x1E, 0xFF, 0x2F, 0xE1
