/* DashDecomp — NODECOMPILED stub
 * Function: sub_00274A70
 * Virtual Address: 0x00274A70
 * File Offset:     0x00174A70
 * Size (bytes):    384
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00274A70
.type   sub_00274A70, %function

sub_00274A70:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 384 bytes at VA 0x00274A70 in build/code.dec.bin
    bx lr
