/* DashDecomp — NODECOMPILED stub
 * Function: sub_0025D144
 * Virtual Address: 0x0025D144
 * File Offset:     0x0015D144
 * Size (bytes):    708
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0025D144
.type   sub_0025D144, %function

sub_0025D144:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 708 bytes at VA 0x0025D144 in build/code.dec.bin
    bx lr
