/* DashDecomp — NODECOMPILED stub
 * Function: sub_00273614
 * Virtual Address: 0x00273614
 * File Offset:     0x00173614
 * Size (bytes):    192
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00273614
.type   sub_00273614, %function

sub_00273614:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 192 bytes at VA 0x00273614 in build/code.dec.bin
    bx lr
