/* DashDecomp — NODECOMPILED stub
 * Function: sub_0023BB1C
 * Virtual Address: 0x0023BB1C
 * File Offset:     0x0013BB1C
 * Size (bytes):    104
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0023BB1C
.type   sub_0023BB1C, %function

sub_0023BB1C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 104 bytes at VA 0x0023BB1C in build/code.dec.bin
    bx lr
