/* DashDecomp — NODECOMPILED stub
 * Function: sub_00244784
 * Virtual Address: 0x00244784
 * File Offset:     0x00144784
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00244784
.type   sub_00244784, %function

sub_00244784:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x00244784 in build/code.dec.bin
    bx lr
