/* DashDecomp — NODECOMPILED stub
 * Function: sub_001F7E2C
 * Virtual Address: 0x001F7E2C
 * File Offset:     0x000F7E2C
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001F7E2C
.type   sub_001F7E2C, %function

sub_001F7E2C:
    .byte 0x00, 0x10, 0x90, 0xE5, 0x01, 0x10, 0x81, 0xE2, 0x0A, 0x00, 0x51, 0xE3, 0x00, 0x10, 0x80, 0xE5
    .byte 0x01, 0x00, 0xA0, 0x83, 0x00, 0x00, 0xA0, 0x93, 0x1E, 0xFF, 0x2F, 0xE1
