/* DashDecomp — NODECOMPILED stub
 * Function: sub_001EBD08
 * Virtual Address: 0x001EBD08
 * File Offset:     0x000EBD08
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001EBD08
.type   sub_001EBD08, %function

sub_001EBD08:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x001EBD08 in build/code.dec.bin
    bx lr
