/* DashDecomp — NODECOMPILED stub
 * Function: sub_00275404
 * Virtual Address: 0x00275404
 * File Offset:     0x00175404
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00275404
.type   sub_00275404, %function

sub_00275404:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x00275404 in build/code.dec.bin
    bx lr
