/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020DAF0
 * Virtual Address: 0x0020DAF0
 * File Offset:     0x0010DAF0
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020DAF0
.type   sub_0020DAF0, %function

sub_0020DAF0:
    .byte 0x0C, 0xC0, 0x9F, 0xE5, 0x04, 0x10, 0x80, 0xE5, 0x00, 0xC0, 0x80, 0xE5, 0xF8, 0x20, 0xC0, 0xE1
    .byte 0x1E, 0xFF, 0x2F, 0xE1
