/* DashDecomp — NODECOMPILED stub
 * Function: sub_002589D8
 * Virtual Address: 0x002589D8
 * File Offset:     0x001589D8
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002589D8
.type   sub_002589D8, %function

sub_002589D8:
    .byte 0x1E, 0xFF, 0x2F, 0xE1
