/* DashDecomp — NODECOMPILED stub
 * Function: sub_00272CFC
 * Virtual Address: 0x00272CFC
 * File Offset:     0x00172CFC
 * Size (bytes):    164
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00272CFC
.type   sub_00272CFC, %function

sub_00272CFC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 164 bytes at VA 0x00272CFC in build/code.dec.bin
    bx lr
