/* DashDecomp — NODECOMPILED stub
 * Function: sub_00241A2C
 * Virtual Address: 0x00241A2C
 * File Offset:     0x00141A2C
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00241A2C
.type   sub_00241A2C, %function

sub_00241A2C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x00241A2C in build/code.dec.bin
    bx lr
