/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020DB28
 * Virtual Address: 0x0020DB28
 * File Offset:     0x0010DB28
 * Size (bytes):    316
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020DB28
.type   sub_0020DB28, %function

sub_0020DB28:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 316 bytes at VA 0x0020DB28 in build/code.dec.bin
    bx lr
