/* DashDecomp — NODECOMPILED stub
 * Function: sub_00248824
 * Virtual Address: 0x00248824
 * File Offset:     0x00148824
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00248824
.type   sub_00248824, %function

sub_00248824:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x00248824 in build/code.dec.bin
    bx lr
