/* DashDecomp — NODECOMPILED stub
 * Function: sub_0021EEDC
 * Virtual Address: 0x0021EEDC
 * File Offset:     0x0011EEDC
 * Size (bytes):    176
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0021EEDC
.type   sub_0021EEDC, %function

sub_0021EEDC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 176 bytes at VA 0x0021EEDC in build/code.dec.bin
    bx lr
