/* DashDecomp — NODECOMPILED stub
 * Function: sub_0027AD84
 * Virtual Address: 0x0027AD84
 * File Offset:     0x0017AD84
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0027AD84
.type   sub_0027AD84, %function

sub_0027AD84:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x0027AD84 in build/code.dec.bin
    bx lr
