/* DashDecomp — NODECOMPILED stub
 * Function: sub_00217654
 * Virtual Address: 0x00217654
 * File Offset:     0x00117654
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00217654
.type   sub_00217654, %function

sub_00217654:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x00217654 in build/code.dec.bin
    bx lr
