/* DashDecomp — NODECOMPILED stub
 * Function: sub_002765E8
 * Virtual Address: 0x002765E8
 * File Offset:     0x001765E8
 * Size (bytes):    140
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002765E8
.type   sub_002765E8, %function

sub_002765E8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 140 bytes at VA 0x002765E8 in build/code.dec.bin
    bx lr
