/* DashDecomp — NODECOMPILED stub
 * Function: sub_0021096C
 * Virtual Address: 0x0021096C
 * File Offset:     0x0011096C
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0021096C
.type   sub_0021096C, %function

sub_0021096C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x0021096C in build/code.dec.bin
    bx lr
