/* DashDecomp — NODECOMPILED stub
 * Function: sub_001F7A90
 * Virtual Address: 0x001F7A90
 * File Offset:     0x000F7A90
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001F7A90
.type   sub_001F7A90, %function

sub_001F7A90:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x001F7A90 in build/code.dec.bin
    bx lr
