/* DashDecomp — NODECOMPILED stub
 * Function: sub_0022373C
 * Virtual Address: 0x0022373C
 * File Offset:     0x0012373C
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_0022373C
.type   sub_0022373C, %function

sub_0022373C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x0022373C in build/code.dec.bin
    bx lr
