/* DashDecomp — NODECOMPILED stub
 * Function: sub_0022EE40
 * Virtual Address: 0x0022EE40
 * File Offset:     0x0012EE40
 * Size (bytes):    284
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0022EE40
.type   sub_0022EE40, %function

sub_0022EE40:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 284 bytes at VA 0x0022EE40 in build/code.dec.bin
    bx lr
