/* DashDecomp — NODECOMPILED stub
 * Function: sub_001FFC6C
 * Virtual Address: 0x001FFC6C
 * File Offset:     0x000FFC6C
 * Size (bytes):    420
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001FFC6C
.type   sub_001FFC6C, %function

sub_001FFC6C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 420 bytes at VA 0x001FFC6C in build/code.dec.bin
    bx lr
