/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020DB0C
 * Virtual Address: 0x0020DB0C
 * File Offset:     0x0010DB0C
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020DB0C
.type   sub_0020DB0C, %function

sub_0020DB0C:
    .byte 0x10, 0x40, 0x2D, 0xE9, 0x5A, 0x0F, 0x00, 0xEB, 0x04, 0x10, 0x9F, 0xE5, 0x00, 0x10, 0x80, 0xE5
    .byte 0x10, 0x80, 0xBD, 0xE8
