/* DashDecomp — NODECOMPILED stub
 * Function: sub_0021DAAC
 * Virtual Address: 0x0021DAAC
 * File Offset:     0x0011DAAC
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0021DAAC
.type   sub_0021DAAC, %function

sub_0021DAAC:
    .byte 0x92, 0x03, 0x02, 0xE0, 0x82, 0x21, 0xA0, 0xE1, 0x00, 0x00, 0xA0, 0xE1
