/* DashDecomp — NODECOMPILED stub
 * Function: sub_00202784
 * Virtual Address: 0x00202784
 * File Offset:     0x00102784
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00202784
.type   sub_00202784, %function

sub_00202784:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x00202784 in build/code.dec.bin
    bx lr
