/* DashDecomp — NODECOMPILED stub
 * Function: sub_00271B4C
 * Virtual Address: 0x00271B4C
 * File Offset:     0x00171B4C
 * Size (bytes):    1912
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00271B4C
.type   sub_00271B4C, %function

sub_00271B4C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1912 bytes at VA 0x00271B4C in build/code.dec.bin
    bx lr
