/* DashDecomp — NODECOMPILED stub
 * Function: sub_001EF80C
 * Virtual Address: 0x001EF80C
 * File Offset:     0x000EF80C
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001EF80C
.type   sub_001EF80C, %function

sub_001EF80C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x001EF80C in build/code.dec.bin
    bx lr
