/* DashDecomp — NODECOMPILED stub
 * Function: sub_002228C0
 * Virtual Address: 0x002228C0
 * File Offset:     0x001228C0
 * Size (bytes):    8
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_002228C0
.type   sub_002228C0, %function

sub_002228C0:
    .byte 0x04, 0x10, 0x91, 0xE5, 0x46, 0x0E, 0xFE, 0xEA
