/* DashDecomp — NODECOMPILED stub
 * Function: sub_0026A08C
 * Virtual Address: 0x0026A08C
 * File Offset:     0x0016A08C
 * Size (bytes):    640
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0026A08C
.type   sub_0026A08C, %function

sub_0026A08C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 640 bytes at VA 0x0026A08C in build/code.dec.bin
    bx lr
