/* DashDecomp — NODECOMPILED stub
 * Function: sub_00230E80
 * Virtual Address: 0x00230E80
 * File Offset:     0x00130E80
 * Size (bytes):    52
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00230E80
.type   sub_00230E80, %function

sub_00230E80:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 52 bytes at VA 0x00230E80 in build/code.dec.bin
    bx lr
