/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020F61C
 * Virtual Address: 0x0020F61C
 * File Offset:     0x0010F61C
 * Size (bytes):    352
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020F61C
.type   sub_0020F61C, %function

sub_0020F61C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 352 bytes at VA 0x0020F61C in build/code.dec.bin
    bx lr
