/* DashDecomp — NODECOMPILED stub
 * Function: sub_00258248
 * Virtual Address: 0x00258248
 * File Offset:     0x00158248
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00258248
.type   sub_00258248, %function

sub_00258248:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 4 bytes at VA 0x00258248 in build/code.dec.bin
    bx lr
