/* DashDecomp — NODECOMPILED stub
 * Function: sub_0026B734
 * Virtual Address: 0x0026B734
 * File Offset:     0x0016B734
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0026B734
.type   sub_0026B734, %function

sub_0026B734:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x0026B734 in build/code.dec.bin
    bx lr
