/* DashDecomp — NODECOMPILED stub
 * Function: sub_00217A64
 * Virtual Address: 0x00217A64
 * File Offset:     0x00117A64
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00217A64
.type   sub_00217A64, %function

sub_00217A64:
    .byte 0x08, 0x10, 0x9F, 0xE5, 0x00, 0x00, 0x90, 0xE5, 0x0C, 0x00, 0x81, 0xE5, 0x1E, 0xFF, 0x2F, 0xE1
