/* DashDecomp — NODECOMPILED stub
 * Function: sub_0020B4CC
 * Virtual Address: 0x0020B4CC
 * File Offset:     0x0010B4CC
 * Size (bytes):    228
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0020B4CC
.type   sub_0020B4CC, %function

sub_0020B4CC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 228 bytes at VA 0x0020B4CC in build/code.dec.bin
    bx lr
