/* DashDecomp — NODECOMPILED stub
 * Function: sub_001EF7AC
 * Virtual Address: 0x001EF7AC
 * File Offset:     0x000EF7AC
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001EF7AC
.type   sub_001EF7AC, %function

sub_001EF7AC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x001EF7AC in build/code.dec.bin
    bx lr
