/* DashDecomp — NODECOMPILED stub
 * Function: sub_0024787C
 * Virtual Address: 0x0024787C
 * File Offset:     0x0014787C
 * Size (bytes):    332
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0024787C
.type   sub_0024787C, %function

sub_0024787C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 332 bytes at VA 0x0024787C in build/code.dec.bin
    bx lr
