/* DashDecomp — NODECOMPILED stub
 * Function: sub_0026CBCC
 * Virtual Address: 0x0026CBCC
 * File Offset:     0x0016CBCC
 * Size (bytes):    64
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0026CBCC
.type   sub_0026CBCC, %function

sub_0026CBCC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 64 bytes at VA 0x0026CBCC in build/code.dec.bin
    bx lr
