/* DashDecomp — NODECOMPILED stub
 * Function: Render::MaterialActivatorFixed::MaterialActivatorFixed(nw::os::IAllocator*, nw::gfx::Material*) [sub_00429EF4]
 * Virtual Address: 0x00429EF4
 * File Offset:     0x00329EF4
 * Size (bytes):    240
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00429EF4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 240 bytes at VA 0x00429EF4 in build/code.dec.bin
    bx lr
