/* DashDecomp — NODECOMPILED stub
 * Function: nn::crypto::Md5Context::ProcessBlock() [sub_002080C4]
 * Virtual Address: 0x002080C4
 * File Offset:     0x001080C4
 * Size (bytes):    328
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

ProcessBlock:  @ was sub_002080C4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 328 bytes at VA 0x002080C4 in build/code.dec.bin
    bx lr
