/* DashDecomp — NODECOMPILED stub
 * Function: Menu3D::SimpleModel::setBaseScale(const sead::Vector3<float>&) [sub_003CB738]
 * Virtual Address: 0x003CB738
 * File Offset:     0x002CB738
 * Size (bytes):    340
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global setBaseScale
.type   setBaseScale, %function

setBaseScale:  @ was sub_003CB738
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 340 bytes at VA 0x003CB738 in build/code.dec.bin
    bx lr
