/* DashDecomp — NODECOMPILED stub
 * Function: Sound::SndVoiceData::loadCannon() [sub_003D2D24]
 * Virtual Address: 0x003D2D24
 * File Offset:     0x002D2D24
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_003D2D24
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x003D2D24 in build/code.dec.bin
    bx lr
