/* DashDecomp — NODECOMPILED stub
 * Function: Menu3D::PreviewPartsBody::inactivate() [sub_003D0984]
 * Virtual Address: 0x003D0984
 * File Offset:     0x002D0984
 * Size (bytes):    236
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global inactivate
.type   inactivate, %function

inactivate:  @ was sub_003D0984
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 236 bytes at VA 0x003D0984 in build/code.dec.bin
    bx lr
