/* DashDecomp — NODECOMPILED stub
 * Function: Enemy::AIControlBattle::stateLockedOn() [sub_00337A70]
 * Virtual Address: 0x00337A70
 * File Offset:     0x00237A70
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00337A70
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x00337A70 in build/code.dec.bin
    bx lr
