/* DashDecomp — NODECOMPILED stub
 * Function: UI::ResultBar::AnimationDefine::defineAnimation() [sub_00162860]
 * Virtual Address: 0x00162860
 * File Offset:     0x00062860
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

defineAnimation:  @ was sub_00162860
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x00162860 in build/code.dec.bin
    bx lr
