/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::internal::driver::Bank::NoteOn(const void*, const nw::snd::internal::driver::NoteOnInfo&, const nw::snd::SoundArchive&, const nw::snd::SoundArchivePlayer&, const nw::snd::internal::PlayerHeapDataManager*) const [sub_004FB2E0]
 * Virtual Address: 0x004FB2E0
 * File Offset:     0x003FB2E0
 * Size (bytes):    452
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_004FB2E0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 452 bytes at VA 0x004FB2E0 in build/code.dec.bin
    bx lr
