/* DashDecomp — NODECOMPILED stub
 * Function: Net::IMatchingManager::createTask(Net::NetworkTaskID) [sub_0026B40C]
 * Virtual Address: 0x0026B40C
 * File Offset:     0x0016B40C
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global createTask
.type   createTask, %function

createTask:  @ was sub_0026B40C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x0026B40C in build/code.dec.bin
    bx lr
