/* DashDecomp — NODECOMPILED stub
 * Function: Net::IMatchingManager::createTask(Net::NetworkTaskID)::sub__1 [sub_0026B4AC]
 * Virtual Address: 0x0026B4AC
 * File Offset:     0x0016B4AC
 * Size (bytes):    8
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_0026B4AC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 8 bytes at VA 0x0026B4AC in build/code.dec.bin
    bx lr
