/* DashDecomp — NODECOMPILED stub
 * Function: Net::IMatchingManager::createBase() [sub_0026B370]
 * Virtual Address: 0x0026B370
 * File Offset:     0x0016B370
 * Size (bytes):    152
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global createBase
.type   createBase, %function

createBase:  @ was sub_0026B370
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 152 bytes at VA 0x0026B370 in build/code.dec.bin
    bx lr
