/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::Key::~Key__deallocating()
 * Virtual Address: 0x001E5314
 * File Offset:     0x000E5314
 * Size (bytes):    152
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Key_deallocating
.type   Key_deallocating, %function

Key_deallocating:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 152 bytes at VA 0x001E5314 in build/code.dec.bin
    bx lr
