/* DashDecomp — NODECOMPILED stub
 * Function: Kart::DispPart::create(const Kart::DispPart::CreateArgs&) [sub_002CDBA8]
 * Virtual Address: 0x002CDBA8
 * File Offset:     0x001CDBA8
 * Size (bytes):    792
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global create
.type   create, %function

create:  @ was sub_002CDBA8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 792 bytes at VA 0x002CDBA8 in build/code.dec.bin
    bx lr
