/* DashDecomp — NODECOMPILED stub
 * Function: Object::CoinManager::CoinManager() [sub_003E08FC]
 * Virtual Address: 0x003E08FC
 * File Offset:     0x002E08FC
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_003E08FC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x003E08FC in build/code.dec.bin
    bx lr
