/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DOCallContext::Cancel(nn::nex::CallContext::State) [sub_001810D0]
 * Virtual Address: 0x001810D0
 * File Offset:     0x000810D0
 * Size (bytes):    812
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

Cancel:  @ was sub_001810D0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 812 bytes at VA 0x001810D0 in build/code.dec.bin
    bx lr
