/* DashDecomp — NODECOMPILED stub
 * Function: sub_0022CD30
 * Virtual Address: 0x0022CD30
 * File Offset:     0x0012CD30
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0022CD30
.type   sub_0022CD30, %function

sub_0022CD30:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x0022CD30 in build/code.dec.bin
    bx lr
