/* DashDecomp — NODECOMPILED stub
 * Function: System::SystemEngine::getMyPlayerData(System::PlayerData*, bool) [sub_004409AC]
 * Virtual Address: 0x004409AC
 * File Offset:     0x003409AC
 * Size (bytes):    168
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004409AC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 168 bytes at VA 0x004409AC in build/code.dec.bin
    bx lr
