/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DOClassTemplate<nn::nex::_DO_Session, nn::nex::_DOC_RootDO>::SpecificRefresh(nn::nex::DuplicatedObject*, nn::nex::DataSet*, const nn::nex::Time&) [sub_005931C0]
 * Virtual Address: 0x005931C0
 * File Offset:     0x004931C0
 * Size (bytes):    220
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_005931C0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 220 bytes at VA 0x005931C0 in build/code.dec.bin
    bx lr
