/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::_DO_SessionClock::CallSyncRequest(nn::nex::RMCContext*, const unsigned long long&) [sub_001ADBCC]
 * Virtual Address: 0x001ADBCC
 * File Offset:     0x000ADBCC
 * Size (bytes):    396
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

CallSyncRequest:  @ was sub_001ADBCC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 396 bytes at VA 0x001ADBCC in build/code.dec.bin
    bx lr
