/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::res::ResGraphicsFile::GetModels(const char*) [sub_00256AA4]
 * Virtual Address: 0x00256AA4
 * File Offset:     0x00156AA4
 * Size (bytes):    112
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00256AA4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 112 bytes at VA 0x00256AA4 in build/code.dec.bin
    bx lr
