/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::SystemErrorResult::IsNexWarning(nn::Result) [sub_001DA650]
 * Virtual Address: 0x001DA650
 * File Offset:     0x000DA650
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_001DA650
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x001DA650 in build/code.dec.bin
    bx lr
