/* DashDecomp — NODECOMPILED stub
 * Function: Render::DrawMdl::InvokePreCalculateMatrix(nw::gfx::Skeleton*, int) [sub_004024E8]
 * Virtual Address: 0x004024E8
 * File Offset:     0x003024E8
 * Size (bytes):    64
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global InvokePreCalculateMatrix
.type   InvokePreCalculateMatrix, %function

InvokePreCalculateMatrix:  @ was sub_004024E8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 64 bytes at VA 0x004024E8 in build/code.dec.bin
    bx lr
