/* DashDecomp — NODECOMPILED stub
 * Function: nw::anim::res::ResAnim::Setup(nw::os::IAllocator*, nw::gfx::res::ResGraphicsFile) [sub_0027E988]
 * Virtual Address: 0x0027E988
 * File Offset:     0x0017E988
 * Size (bytes):    160
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0027E988
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 160 bytes at VA 0x0027E988 in build/code.dec.bin
    bx lr
