/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::_DO_PromotionReferee::_DO_PromotionReferee() [sub_0011D938]
 * Virtual Address: 0x0011D938
 * File Offset:     0x0001D938
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0011D938
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x0011D938 in build/code.dec.bin
    bx lr
