/* DashDecomp — NODECOMPILED stub
 * Function: nn::uds::CTR::detail::Uds::Finalize() [sub_00203D28]
 * Virtual Address: 0x00203D28
 * File Offset:     0x00103D28
 * Size (bytes):    120
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Finalize
.type   Finalize, %function

Finalize:  @ was sub_00203D28
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 120 bytes at VA 0x00203D28 in build/code.dec.bin
    bx lr
