/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectIronBall::getDTIClassStatic() [sub_00340F90]
 * Virtual Address: 0x00340F90
 * File Offset:     0x00240F90
 * Size (bytes):    436
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global getDTIClassStatic
.type   getDTIClassStatic, %function

getDTIClassStatic:  @ was sub_00340F90
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 436 bytes at VA 0x00340F90 in build/code.dec.bin
    bx lr
