/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectIronBall::setReaction_fromKart(Field::EGHTReaction, Field::eObjectReactType, Kart::VehicleReact*)
 * Virtual Address: 0x003412E0
 * File Offset:     0x002412E0
 * Size (bytes):    148
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global setReaction_fromKart
.type   setReaction_fromKart, %function

setReaction_fromKart:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 148 bytes at VA 0x003412E0 in build/code.dec.bin
    bx lr
