/* DashDecomp — NODECOMPILED stub
 * Function: sead::RamStreamSrc::read(void*, unsigned) [sub_0030A328]
 * Virtual Address: 0x0030A328
 * File Offset:     0x0020A328
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0030A328
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x0030A328 in build/code.dec.bin
    bx lr
