/* DashDecomp — NODECOMPILED stub
 * Function: System::KDThread::KDThread__sub_object(const sead::SafeStringBase<char>&, EThreadPriority, int, int, bool) [sub_00106BD0]
 * Virtual Address: 0x00106BD0
 * File Offset:     0x00006BD0
 * Size (bytes):    176
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00106BD0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 176 bytes at VA 0x00106BD0 in build/code.dec.bin
    bx lr
