/* DashDecomp — NODECOMPILED stub
 * Function: UI::BasePointControl::setNum(int) [sub_00145238]
 * Virtual Address: 0x00145238
 * File Offset:     0x00045238
 * Size (bytes):    252
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_00145238
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 252 bytes at VA 0x00145238 in build/code.dec.bin
    bx lr
