/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::PRUDPStream::RemoveCIDEndPointAssociation(unsigned, nn::nex::EndPoint*) [sub_0017402C]
 * Virtual Address: 0x0017402C
 * File Offset:     0x0007402C
 * Size (bytes):    480
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

RemoveCIDEndPointAssociation:  @ was sub_0017402C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 480 bytes at VA 0x0017402C in build/code.dec.bin
    bx lr
