/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectCmnCarCollision::initScaleInner() [sub_0037842C]
 * Virtual Address: 0x0037842C
 * File Offset:     0x0027842C
 * Size (bytes):    708
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global initScaleInner
.type   initScaleInner, %function

initScaleInner:  @ was sub_0037842C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 708 bytes at VA 0x0037842C in build/code.dec.bin
    bx lr
