/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DataStoreClientTemplate<nn::nex::DataStoreLogicServerClient>::PostObjectImpl(nn::nex::ProtocolCallContext*, const nn::nex::DataStorePreparePostParam&, unsigned*, nn::nex::DataStorePostObjectEventListener*, const unsigned char*, bool) [sub_00594E78]
 * Virtual Address: 0x00594E78
 * File Offset:     0x00494E78
 * Size (bytes):    328
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00594E78
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 328 bytes at VA 0x00594E78 in build/code.dec.bin
    bx lr
