/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::Credentials::MarkInvalid() [sub_00198460]
 * Virtual Address: 0x00198460
 * File Offset:     0x00098460
 * Size (bytes):    20
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00198460
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 20 bytes at VA 0x00198460 in build/code.dec.bin
    bx lr
