/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DateTime::operator =(const nn::nex::DateTime&) [sub_0021AF9C]
 * Virtual Address: 0x0021AF9C
 * File Offset:     0x0011AF9C
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0021AF9C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x0021AF9C in build/code.dec.bin
    bx lr
