/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::_Type_qlist<nn::nex::_Type_dohandle>::Extract(nn::nex::Message*, nn::nex::qList<nn::nex::DOHandle>*) [sub_00590DD4]
 * Virtual Address: 0x00590DD4
 * File Offset:     0x00490DD4
 * Size (bytes):    376
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00590DD4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 376 bytes at VA 0x00590DD4 in build/code.dec.bin
    bx lr
