/* DashDecomp — NODECOMPILED stub
 * Function: UI::ControlAnimator::AnimationItem::AnimationItem__sub_object(const sead::SafeStringBase<char>&) [sub_0015A360]
 * Virtual Address: 0x0015A360
 * File Offset:     0x0005A360
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0015A360
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x0015A360 in build/code.dec.bin
    bx lr
