/* DashDecomp — NODECOMPILED stub
 * Function: nw::anim::AnimBlendOpInt::ConvertToAnimResult(nw::anim::AnimResult*, const void*) const
 * Virtual Address: 0x004A38E0
 * File Offset:     0x003A38E0
 * Size (bytes):    888
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ConvertToAnimResult
.type   ConvertToAnimResult, %function

ConvertToAnimResult:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 888 bytes at VA 0x004A38E0 in build/code.dec.bin
    bx lr
