/* DashDecomp — NODECOMPILED stub
 * Function: nn::gxlow::CTR::Gpu::TriggerCmdReqQueue() [sub_00113358]
 * Virtual Address: 0x00113358
 * File Offset:     0x00013358
 * Size (bytes):    40
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00113358
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 40 bytes at VA 0x00113358 in build/code.dec.bin
    bx lr
