/* DashDecomp — NODECOMPILED stub
 * Function: Sound::SndActorKart::setType(int)
 * Virtual Address: 0x0039F1D4
 * File Offset:     0x0029F1D4
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global Sound_SndActorKart_setType
.type   Sound_SndActorKart_setType, %function

Sound_SndActorKart_setType:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x0039F1D4 in build/code.dec.bin
    bx lr
