/* DashDecomp — NODECOMPILED stub
 * Function: sub_00399C34
 * Virtual Address: 0x00399C34
 * File Offset:     0x00299C34
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00399C34
.type   sub_00399C34, %function

sub_00399C34:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x00399C34 in build/code.dec.bin
    bx lr
