/* DashDecomp — NODECOMPILED stub
 * Function: sub_003CB89C
 * Virtual Address: 0x003CB89C
 * File Offset:     0x002CB89C
 * Size (bytes):    196
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003CB89C
.type   sub_003CB89C, %function

sub_003CB89C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 196 bytes at VA 0x003CB89C in build/code.dec.bin
    bx lr
