/* DashDecomp — NODECOMPILED stub
 * Function: sub_0040B490
 * Virtual Address: 0x0040B490
 * File Offset:     0x0030B490
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0040B490
.type   sub_0040B490, %function

sub_0040B490:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x0040B490 in build/code.dec.bin
    bx lr
