/* DashDecomp — NODECOMPILED stub
 * Function: sub_003C2664
 * Virtual Address: 0x003C2664
 * File Offset:     0x002C2664
 * Size (bytes):    136
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003C2664
.type   sub_003C2664, %function

sub_003C2664:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 136 bytes at VA 0x003C2664 in build/code.dec.bin
    bx lr
