/* DashDecomp — NODECOMPILED stub
 * Function: sub_003A7AAC
 * Virtual Address: 0x003A7AAC
 * File Offset:     0x002A7AAC
 * Size (bytes):    128
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003A7AAC
.type   sub_003A7AAC, %function

sub_003A7AAC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 128 bytes at VA 0x003A7AAC in build/code.dec.bin
    bx lr
