/* DashDecomp — NODECOMPILED stub
 * Function: sub_00432BC4
 * Virtual Address: 0x00432BC4
 * File Offset:     0x00332BC4
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00432BC4
.type   sub_00432BC4, %function

sub_00432BC4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x00432BC4 in build/code.dec.bin
    bx lr
