/* DashDecomp — NODECOMPILED stub
 * Function: sub_003DA930
 * Virtual Address: 0x003DA930
 * File Offset:     0x002DA930
 * Size (bytes):    740
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003DA930
.type   sub_003DA930, %function

sub_003DA930:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 740 bytes at VA 0x003DA930 in build/code.dec.bin
    bx lr
