/* DashDecomp — NODECOMPILED stub
 * Function: sub_003A3DC4
 * Virtual Address: 0x003A3DC4
 * File Offset:     0x002A3DC4
 * Size (bytes):    128
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003A3DC4
.type   sub_003A3DC4, %function

sub_003A3DC4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 128 bytes at VA 0x003A3DC4 in build/code.dec.bin
    bx lr
