/* DashDecomp — NODECOMPILED stub
 * Function: sub_00443DFC
 * Virtual Address: 0x00443DFC
 * File Offset:     0x00343DFC
 * Size (bytes):    248
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00443DFC
.type   sub_00443DFC, %function

sub_00443DFC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 248 bytes at VA 0x00443DFC in build/code.dec.bin
    bx lr
