/* DashDecomp — NODECOMPILED stub
 * Function: sub_00450B9C
 * Virtual Address: 0x00450B9C
 * File Offset:     0x00350B9C
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00450B9C
.type   sub_00450B9C, %function

sub_00450B9C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x00450B9C in build/code.dec.bin
    bx lr
