/* DashDecomp — NODECOMPILED stub
 * Function: sub_003A0838
 * Virtual Address: 0x003A0838
 * File Offset:     0x002A0838
 * Size (bytes):    672
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003A0838
.type   sub_003A0838, %function

sub_003A0838:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 672 bytes at VA 0x003A0838 in build/code.dec.bin
    bx lr
