/* DashDecomp — NODECOMPILED stub
 * Function: sub_0046770C
 * Virtual Address: 0x0046770C
 * File Offset:     0x0036770C
 * Size (bytes):    1020
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0046770C
.type   sub_0046770C, %function

sub_0046770C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1020 bytes at VA 0x0046770C in build/code.dec.bin
    bx lr
