/* DashDecomp — NODECOMPILED stub
 * Function: sub_0044EE1C
 * Virtual Address: 0x0044EE1C
 * File Offset:     0x0034EE1C
 * Size (bytes):    104
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0044EE1C
.type   sub_0044EE1C, %function

sub_0044EE1C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 104 bytes at VA 0x0044EE1C in build/code.dec.bin
    bx lr
