/* DashDecomp — NODECOMPILED stub
 * Function: sub_0038F384
 * Virtual Address: 0x0038F384
 * File Offset:     0x0028F384
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0038F384
.type   sub_0038F384, %function

sub_0038F384:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x0038F384 in build/code.dec.bin
    bx lr
