/* DashDecomp — NODECOMPILED stub
 * Function: sub_0045E6DC
 * Virtual Address: 0x0045E6DC
 * File Offset:     0x0035E6DC
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_0045E6DC
.type   sub_0045E6DC, %function

sub_0045E6DC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ See the original asm at VA 0x0045E6DC in build/code.dec.bin
    bx lr
