/* DashDecomp — NODECOMPILED stub
 * Function: sub_003EA7F4
 * Virtual Address: 0x003EA7F4
 * File Offset:     0x002EA7F4
 * Size (bytes):    1956
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003EA7F4
.type   sub_003EA7F4, %function

sub_003EA7F4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1956 bytes at VA 0x003EA7F4 in build/code.dec.bin
    bx lr
