/* DashDecomp — NODECOMPILED stub
 * Function: sub_0044BE78
 * Virtual Address: 0x0044BE78
 * File Offset:     0x0034BE78
 * Size (bytes):    172
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0044BE78
.type   sub_0044BE78, %function

sub_0044BE78:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 172 bytes at VA 0x0044BE78 in build/code.dec.bin
    bx lr
