/* DashDecomp — NODECOMPILED stub
 * Function: sub_003C5F18
 * Virtual Address: 0x003C5F18
 * File Offset:     0x002C5F18
 * Size (bytes):    424
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003C5F18
.type   sub_003C5F18, %function

sub_003C5F18:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 424 bytes at VA 0x003C5F18 in build/code.dec.bin
    bx lr
