/* DashDecomp — NODECOMPILED stub
 * Function: sub_00384478
 * Virtual Address: 0x00384478
 * File Offset:     0x00284478
 * Size (bytes):    660
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00384478
.type   sub_00384478, %function

sub_00384478:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 660 bytes at VA 0x00384478 in build/code.dec.bin
    bx lr
