/* DashDecomp — NODECOMPILED stub
 * Function: sub_00433DBC
 * Virtual Address: 0x00433DBC
 * File Offset:     0x00333DBC
 * Size (bytes):    44
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00433DBC
.type   sub_00433DBC, %function

sub_00433DBC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 44 bytes at VA 0x00433DBC in build/code.dec.bin
    bx lr
