/* DashDecomp — NODECOMPILED stub
 * Function: sub_00400FFC
 * Virtual Address: 0x00400FFC
 * File Offset:     0x00300FFC
 * Size (bytes):    144
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00400FFC
.type   sub_00400FFC, %function

sub_00400FFC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 144 bytes at VA 0x00400FFC in build/code.dec.bin
    bx lr
