/* DashDecomp — NODECOMPILED stub
 * Function: sub_003C2888
 * Virtual Address: 0x003C2888
 * File Offset:     0x002C2888
 * Size (bytes):    168
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003C2888
.type   sub_003C2888, %function

sub_003C2888:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 168 bytes at VA 0x003C2888 in build/code.dec.bin
    bx lr
