/* DashDecomp — NODECOMPILED stub
 * Function: sub_00447BE0
 * Virtual Address: 0x00447BE0
 * File Offset:     0x00347BE0
 * Size (bytes):    252
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00447BE0
.type   sub_00447BE0, %function

sub_00447BE0:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 252 bytes at VA 0x00447BE0 in build/code.dec.bin
    bx lr
