/* DashDecomp — NODECOMPILED stub
 * Function: sub_0044DAC4
 * Virtual Address: 0x0044DAC4
 * File Offset:     0x0034DAC4
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0044DAC4
.type   sub_0044DAC4, %function

sub_0044DAC4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x0044DAC4 in build/code.dec.bin
    bx lr
