/* DashDecomp — NODECOMPILED stub
 * Function: sub_004562B4
 * Virtual Address: 0x004562B4
 * File Offset:     0x003562B4
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004562B4
.type   sub_004562B4, %function

sub_004562B4:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x004562B4 in build/code.dec.bin
    bx lr
