/* DashDecomp — NODECOMPILED stub
 * Function: sub_003CA61C
 * Virtual Address: 0x003CA61C
 * File Offset:     0x002CA61C
 * Size (bytes):    580
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003CA61C
.type   sub_003CA61C, %function

sub_003CA61C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 580 bytes at VA 0x003CA61C in build/code.dec.bin
    bx lr
