/* DashDecomp — NODECOMPILED stub
 * Function: sub_003997E8
 * Virtual Address: 0x003997E8
 * File Offset:     0x002997E8
 * Size (bytes):    164
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003997E8
.type   sub_003997E8, %function

sub_003997E8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 164 bytes at VA 0x003997E8 in build/code.dec.bin
    bx lr
