/* DashDecomp — NODECOMPILED stub
 * Function: sub_004460A8
 * Virtual Address: 0x004460A8
 * File Offset:     0x003460A8
 * Size (bytes):    1248
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_004460A8
.type   sub_004460A8, %function

sub_004460A8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1248 bytes at VA 0x004460A8 in build/code.dec.bin
    bx lr
