/* DashDecomp — NODECOMPILED stub
 * Function: sub_003BD888
 * Virtual Address: 0x003BD888
 * File Offset:     0x002BD888
 * Size (bytes):    196
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003BD888
.type   sub_003BD888, %function

sub_003BD888:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 196 bytes at VA 0x003BD888 in build/code.dec.bin
    bx lr
