/* DashDecomp — NODECOMPILED stub
 * Function: sub_0044C85C
 * Virtual Address: 0x0044C85C
 * File Offset:     0x0034C85C
 * Size (bytes):    120
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0044C85C
.type   sub_0044C85C, %function

sub_0044C85C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 120 bytes at VA 0x0044C85C in build/code.dec.bin
    bx lr
