/* DashDecomp — NODECOMPILED stub
 * Function: sub_0039A028
 * Virtual Address: 0x0039A028
 * File Offset:     0x0029A028
 * Size (bytes):    252
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0039A028
.type   sub_0039A028, %function

sub_0039A028:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 252 bytes at VA 0x0039A028 in build/code.dec.bin
    bx lr
