/* DashDecomp — NODECOMPILED stub
 * Function: sub_003FA984
 * Virtual Address: 0x003FA984
 * File Offset:     0x002FA984
 * Size (bytes):    176
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_003FA984
.type   sub_003FA984, %function

sub_003FA984:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 176 bytes at VA 0x003FA984 in build/code.dec.bin
    bx lr
