/* DashDecomp — NODECOMPILED stub
 * Function: sub_00383FD8
 * Virtual Address: 0x00383FD8
 * File Offset:     0x00283FD8
 * Size (bytes):    140
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00383FD8
.type   sub_00383FD8, %function

sub_00383FD8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 140 bytes at VA 0x00383FD8 in build/code.dec.bin
    bx lr
