/* DashDecomp — NODECOMPILED stub
 * Function: sub_0046FE24
 * Virtual Address: 0x0046FE24
 * File Offset:     0x0036FE24
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0046FE24
.type   sub_0046FE24, %function

sub_0046FE24:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x0046FE24 in build/code.dec.bin
    bx lr
