/* DashDecomp — NODECOMPILED stub
 * Function: sub_0039813C
 * Virtual Address: 0x0039813C
 * File Offset:     0x0029813C
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0039813C
.type   sub_0039813C, %function

sub_0039813C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x0039813C in build/code.dec.bin
    bx lr
