/* DashDecomp — NODECOMPILED stub
 * Function: sub_0044817C
 * Virtual Address: 0x0044817C
 * File Offset:     0x0034817C
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0044817C
.type   sub_0044817C, %function

sub_0044817C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x0044817C in build/code.dec.bin
    bx lr
