/* DashDecomp — NODECOMPILED stub
 * Function: sub_00418294
 * Virtual Address: 0x00418294
 * File Offset:     0x00318294
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00418294
.type   sub_00418294, %function

sub_00418294:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x00418294 in build/code.dec.bin
    bx lr
