/* DashDecomp — NODECOMPILED stub
 * Function: sub_0044A27C
 * Virtual Address: 0x0044A27C
 * File Offset:     0x0034A27C
 * Size (bytes):    208
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_0044A27C
.type   sub_0044A27C, %function

sub_0044A27C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 208 bytes at VA 0x0044A27C in build/code.dec.bin
    bx lr
