/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::MenuChannel_SetupGP::getDTIClass() const [sub_004C0928]
 * Virtual Address: 0x004C0928
 * File Offset:     0x003C0928
 * Size (bytes):    92
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global getDTIClass
.type   getDTIClass, %function

getDTIClass:  @ was sub_004C0928
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 92 bytes at VA 0x004C0928 in build/code.dec.bin
    bx lr
