/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectSnowMan::calcObj() [sub_00365878]
 * Virtual Address: 0x00365878
 * File Offset:     0x00265878
 * Size (bytes):    296
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00365878
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 296 bytes at VA 0x00365878 in build/code.dec.bin
    bx lr
