/* DashDecomp — NODECOMPILED stub
 * Function: Render::MaterialActivatorBufferNW::Activate(nw::gfx::RenderContext*, const nw::gfx::Material*) [sub_003F56E4]
 * Virtual Address: 0x003F56E4
 * File Offset:     0x002F56E4
 * Size (bytes):    456
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

Activate:  @ was sub_003F56E4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 456 bytes at VA 0x003F56E4 in build/code.dec.bin
    bx lr
