/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectHanachanPart::doReaction_againstKart(Field::EGHTReaction, Kart::VehicleReact*, Field::ObjectCollisionResult*, bool) [sub_0039A028]
 * Virtual Address: 0x0039A028
 * File Offset:     0x0029A028
 * Size (bytes):    252
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0039A028
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 252 bytes at VA 0x0039A028 in build/code.dec.bin
    bx lr
