/* DashDecomp — NODECOMPILED stub
 * Function: __rw::__rb_tree<unsigned, std::pair<const unsigned, nn::nex::Ticket*>, __rw::__select1st<std::pair<const unsigned, nn::nex::Ticket*>, unsigned>, std::less<unsigned>, nn::nex::MemAllocator<std::pair<const unsigned, nn::nex::Ticket*>>>::_C_insert(__rw::__rw_rb_tree_node<nn::nex::MemAllocator<std::pair<const unsigned, nn::nex::Ticket*>>, std::pair<const unsigned, nn::nex::Ticket*>, unsigned, __rw::__select1st<std::pair<const unsigned, nn::nex::Ticket*>, unsigned>>*, __rw::__rw_rb_tree_node<nn::nex::MemAllocator<std::pair<const unsigned, nn::nex::Ticket*>>, std::pair<const unsigned, nn::nex::Ticket*>, unsigned, __rw::__select1st<std::pair<const unsigned, nn::nex::Ticket*>, unsigned>>*, const std::pair<const unsigned, nn::nex::Ticket*>&)::sub__1 [sub_00559CEC]
 * Virtual Address: 0x00559CEC
 * File Offset:     0x00459CEC
 * Size (bytes):    56
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_00559CEC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 56 bytes at VA 0x00559CEC in build/code.dec.bin
    bx lr
