/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::DataStoreProtocolClient::~DataStoreProtocolClient__deallocating() [sub_001D696C]
 * Virtual Address: 0x001D696C
 * File Offset:     0x000D696C
 * Size (bytes):    388
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

DataStoreProtocolClient_deallocating:  @ was sub_001D696C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 388 bytes at VA 0x001D696C in build/code.dec.bin
    bx lr
