/* DashDecomp — NODECOMPILED stub
 * Function: sead::BufferedSafeStringBase<char>::format(const char*, ...) [sub_002E31A0]
 * Virtual Address: 0x002E31A0
 * File Offset:     0x001E31A0
 * Size (bytes):    1280
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global format
.type   format, %function

format:  @ was sub_002E31A0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1280 bytes at VA 0x002E31A0 in build/code.dec.bin
    bx lr
