/* DashDecomp — NODECOMPILED stub
 * Function: Net::NetworkGameEventMgr::Buffer::setSendEvent(Net::NetworkGameEventMgr::EventType, int, void*, int, unsigned) [sub_0029DEA0]
 * Virtual Address: 0x0029DEA0
 * File Offset:     0x0019DEA0
 * Size (bytes):    140
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_0029DEA0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 140 bytes at VA 0x0029DEA0 in build/code.dec.bin
    bx lr
