/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::ParallelSequence::finish(Sequence::Section::EFadeKind, unsigned) [sub_0044E944]
 * Virtual Address: 0x0044E944
 * File Offset:     0x0034E944
 * Size (bytes):    452
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global finish
.type   finish, %function

finish:  @ was sub_0044E944
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 452 bytes at VA 0x0044E944 in build/code.dec.bin
    bx lr
