/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::_DDL_RankingData::operator =(const nn::nex::_DDL_RankingData&) [sub_001ACCE8]
 * Virtual Address: 0x001ACCE8
 * File Offset:     0x000ACCE8
 * Size (bytes):    2688
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global operator
.type   operator, %function

operator:  @ was sub_001ACCE8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 2688 bytes at VA 0x001ACCE8 in build/code.dec.bin
    bx lr
