/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::CalculatedTransform::SetRotateXYZ(float, float, float) [sub_0022378C]
 * Virtual Address: 0x0022378C
 * File Offset:     0x0012378C
 * Size (bytes):    356
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global SetRotateXYZ
.type   SetRotateXYZ, %function

SetRotateXYZ:  @ was sub_0022378C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 356 bytes at VA 0x0022378C in build/code.dec.bin
    bx lr
