/* DashDecomp — NODECOMPILED stub
 * Function: UI::GessoControl::onReset() [sub_0014F058]
 * Virtual Address: 0x0014F058
 * File Offset:     0x0004F058
 * Size (bytes):    120
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_0014F058
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 120 bytes at VA 0x0014F058 in build/code.dec.bin
    bx lr
