/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectWayBase::calcObj() [sub_003380C4]
 * Virtual Address: 0x003380C4
 * File Offset:     0x002380C4
 * Size (bytes):    380
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global calcObj
.type   calcObj, %function

calcObj:  @ was sub_003380C4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 380 bytes at VA 0x003380C4 in build/code.dec.bin
    bx lr
