/* DashDecomp — NODECOMPILED stub
 * Function: nn::os::detail::ConvertSvcToLibraryPriority(int) [sub_00111154]
 * Virtual Address: 0x00111154
 * File Offset:     0x00011154
 * Size (bytes):    312
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

ConvertSvcToLibraryPriority:  @ was sub_00111154
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 312 bytes at VA 0x00111154 in build/code.dec.bin
    bx lr
