/* DashDecomp — NODECOMPILED stub
 * Function: UI::WipeFaderControl::getDTIClass() const [sub_0048BB48]
 * Virtual Address: 0x0048BB48
 * File Offset:     0x0038BB48
 * Size (bytes):    136
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global getDTIClass
.type   getDTIClass, %function

getDTIClass:  @ was sub_0048BB48
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 136 bytes at VA 0x0048BB48 in build/code.dec.bin
    bx lr
