/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::TransformAnimInterpolator::~TransformAnimInterpolator() [sub_00228AE4]
 * Virtual Address: 0x00228AE4
 * File Offset:     0x00128AE4
 * Size (bytes):    252
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global TransformAnimInterpolator
.type   TransformAnimInterpolator, %function

TransformAnimInterpolator:  @ was sub_00228AE4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 252 bytes at VA 0x00228AE4 in build/code.dec.bin
    bx lr
