/* DashDecomp — NODECOMPILED stub
 * Function: Effect::ParticleDirector::entryResource(const sead::SafeStringBase<char>&, sead::Heap*, void*, int) [sub_003BFCAC]
 * Virtual Address: 0x003BFCAC
 * File Offset:     0x002BFCAC
 * Size (bytes):    940
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

entryResource:  @ was sub_003BFCAC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 940 bytes at VA 0x003BFCAC in build/code.dec.bin
    bx lr
