/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::internal::SoundArchiveFile::InfoBlockBody::GetWaveArchiveInfo(unsigned) const [sub_004F9DC8]
 * Virtual Address: 0x004F9DC8
 * File Offset:     0x003F9DC8
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004F9DC8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x004F9DC8 in build/code.dec.bin
    bx lr
