/* DashDecomp — NODECOMPILED stub
 * Function: Item::ItemObjGesso::calc_HitWall(const KDGndCol::HitInfo&) [sub_00290024]
 * Virtual Address: 0x00290024
 * File Offset:     0x00190024
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global calc_HitWall
.type   calc_HitWall, %function

calc_HitWall:  @ was sub_00290024
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x00290024 in build/code.dec.bin
    bx lr
