/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::Fog::CreateAnimGroup(nw::os::IAllocator*) [sub_00253FF4]
 * Virtual Address: 0x00253FF4
 * File Offset:     0x00153FF4
 * Size (bytes):    412
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00253FF4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 412 bytes at VA 0x00253FF4 in build/code.dec.bin
    bx lr
