/* DashDecomp — NODECOMPILED stub
 * Function: Util::KDRailUpdater::reset(int, float) [sub_003032D4]
 * Virtual Address: 0x003032D4
 * File Offset:     0x002032D4
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_003032D4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x003032D4 in build/code.dec.bin
    bx lr
