/* DashDecomp — NODECOMPILED stub
 * Function: Enemy::TargetSearcher<unsigned short>::getTarget(unsigned short, sead::Vector3<float>*, int*) [sub_005C01BC]
 * Virtual Address: 0x005C01BC
 * File Offset:     0x004C01BC
 * Size (bytes):    112
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_005C01BC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 112 bytes at VA 0x005C01BC in build/code.dec.bin
    bx lr
