/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::MenuChannel_Top::canFinishFadeout()
 * Virtual Address: 0x0044150C
 * File Offset:     0x0034150C
 * Size (bytes):    228
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: DLP xmap (direct VA match)
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global canFinishFadeout
.type   canFinishFadeout, %function

canFinishFadeout:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 228 bytes at VA 0x0044150C in build/code.dec.bin
    bx lr
