/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::MenuChannel_Top::onSliderSetting(bool, bool) [sub_00440EE8]
 * Virtual Address: 0x00440EE8
 * File Offset:     0x00340EE8
 * Size (bytes):    1440
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global onSliderSetting
.type   onSliderSetting, %function

onSliderSetting:  @ was sub_00440EE8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1440 bytes at VA 0x00440EE8 in build/code.dec.bin
    bx lr
