/* DashDecomp — NODECOMPILED stub
 * Function: KDGndCol::HitInfoImpl::entryAttrW(unsigned, unsigned short, unsigned, float) [sub_004232AC]
 * Virtual Address: 0x004232AC
 * File Offset:     0x003232AC
 * Size (bytes):    248
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global entryAttrW
.type   entryAttrW, %function

entryAttrW:  @ was sub_004232AC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 248 bytes at VA 0x004232AC in build/code.dec.bin
    bx lr
