/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectPukupuku::calcPosIncludeLOD(bool, bool, const sead::Matrix34<float>&) [sub_00343144]
 * Virtual Address: 0x00343144
 * File Offset:     0x00243144
 * Size (bytes):    196
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

calcPosIncludeLOD:  @ was sub_00343144
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 196 bytes at VA 0x00343144 in build/code.dec.bin
    bx lr
