/* DashDecomp — NODECOMPILED stub
 * Function: sub_001A5F64
 * Virtual Address: 0x001A5F64
 * File Offset:     0x000A5F64
 * Size (bytes):    128
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_001A5F64
.type   sub_001A5F64, %function

sub_001A5F64:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 128 bytes at VA 0x001A5F64 in build/code.dec.bin
    bx lr
