/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectSnowMan::setReaction_fromKart(Field::EGHTReaction, Field::eObjectReactType, Kart::VehicleReact*) [sub_00335F84]
 * Virtual Address: 0x00335F84
 * File Offset:     0x00235F84
 * Size (bytes):    564
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

setReaction_fromKart:  @ was sub_00335F84
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 564 bytes at VA 0x00335F84 in build/code.dec.bin
    bx lr
