/* DashDecomp — NODECOMPILED stub
 * Function: Item::KartItem::_calcNetKartSubIcon() [sub_002A2A88]
 * Virtual Address: 0x002A2A88
 * File Offset:     0x001A2A88
 * Size (bytes):    436
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

calcNetKartSubIcon:  @ was sub_002A2A88
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 436 bytes at VA 0x002A2A88 in build/code.dec.bin
    bx lr
