/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::RenderContext::ActivateFragmentLight(int, const nw::gfx::FragmentLight*) [sub_0021A4A0]
 * Virtual Address: 0x0021A4A0
 * File Offset:     0x0011A4A0
 * Size (bytes):    160
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ActivateFragmentLight
.type   ActivateFragmentLight, %function

ActivateFragmentLight:  @ was sub_0021A4A0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 160 bytes at VA 0x0021A4A0 in build/code.dec.bin
    bx lr
