/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::Menu_UpBarController::setupKartSelectedBar() [sub_0046AAE4]
 * Virtual Address: 0x0046AAE4
 * File Offset:     0x0036AAE4
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_0046AAE4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 4 bytes at VA 0x0046AAE4 in build/code.dec.bin
    bx lr
