/* DashDecomp — NODECOMPILED stub
 * Function: Item::ItemReactProxy::ItemReactProxy(Item::ItemObjBase*) [sub_0029DFDC]
 * Virtual Address: 0x0029DFDC
 * File Offset:     0x0019DFDC
 * Size (bytes):    232
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ItemReactProxy
.type   ItemReactProxy, %function

ItemReactProxy:  @ was sub_0029DFDC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 232 bytes at VA 0x0029DFDC in build/code.dec.bin
    bx lr
