/* DashDecomp — NODECOMPILED stub
 * Function: sub_005A3474
 * Virtual Address: 0x005A3474
 * File Offset:     0x004A3474
 * Size (bytes):    1640
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005A3474
.type   sub_005A3474, %function

sub_005A3474:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 1640 bytes at VA 0x005A3474 in build/code.dec.bin
    bx lr
