/* DashDecomp — NODECOMPILED stub
 * Function: sub_005A3B24
 * Virtual Address: 0x005A3B24
 * File Offset:     0x004A3B24
 * Size (bytes):    996
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005A3B24
.type   sub_005A3B24, %function

sub_005A3B24:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 996 bytes at VA 0x005A3B24 in build/code.dec.bin
    bx lr
