/* DashDecomp — NODECOMPILED stub
 * Function: sub_00590D60
 * Virtual Address: 0x00590D60
 * File Offset:     0x00490D60
 * Size (bytes):    25206
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/create_stubs.py
 * To decompile: create a scratch at decomp.me and write matching C++.
 * Then replace this file with your .cpp in src/ and open a PR.
 */

.section .text
.global sub_00590D60
.type   sub_00590D60, %function

sub_00590D60:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 25206 bytes at VA 0x00590D60 in build/code.dec.bin
    bx lr
