/* DashDecomp — NODECOMPILED stub
 * Function: UI::CursorMove::next_GameSetting(UI::CursorItem*) [sub_00142320]
 * Virtual Address: 0x00142320
 * File Offset:     0x00042320
 * Size (bytes):    260
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00142320
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 260 bytes at VA 0x00142320 in build/code.dec.bin
    bx lr
