/* DashDecomp — NODECOMPILED stub
 * Function: sead::DoubleCmdGameFrameworkCtrNw4c::presentBtm_() [sub_00313DE4]
 * Virtual Address: 0x00313DE4
 * File Offset:     0x00213DE4
 * Size (bytes):    80
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00313DE4
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 80 bytes at VA 0x00313DE4 in build/code.dec.bin
    bx lr
