/* DashDecomp — NODECOMPILED stub
 * Function: Net::NetworkSupplyInfoManager::~NetworkSupplyInfoManager() [sub_0027A954]
 * Virtual Address: 0x0027A954
 * File Offset:     0x0017A954
 * Size (bytes):    112
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global NetworkSupplyInfoManager
.type   NetworkSupplyInfoManager, %function

NetworkSupplyInfoManager:  @ was sub_0027A954
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 112 bytes at VA 0x0027A954 in build/code.dec.bin
    bx lr
