/* DashDecomp — NODECOMPILED stub
 * Function: Object::Actor::renderMainROuter() [sub_0041F028]
 * Virtual Address: 0x0041F028
 * File Offset:     0x0031F028
 * Size (bytes):    12
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0041F028
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 12 bytes at VA 0x0041F028 in build/code.dec.bin
    bx lr
