/* DashDecomp — NODECOMPILED stub
 * Function: sub_005D797C
 * Virtual Address: 0x005D797C
 * File Offset:     0x004D797C
 * Size (bytes):    132
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005D797C
.type   sub_005D797C, %function

sub_005D797C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 132 bytes at VA 0x005D797C in build/code.dec.bin
    bx lr
