/* DashDecomp — NODECOMPILED stub
 * Function: sub_005C9ACC
 * Virtual Address: 0x005C9ACC
 * File Offset:     0x004C9ACC
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005C9ACC
.type   sub_005C9ACC, %function

sub_005C9ACC:
    .byte 0x08, 0x40, 0x2D, 0xE9, 0x08, 0xC0, 0x9D, 0xE5, 0x00, 0xC0, 0x8D, 0xE5, 0x00, 0xC0, 0x90, 0xE5
    .byte 0x18, 0xC0, 0x9C, 0xE5, 0x3C, 0xFF, 0x2F, 0xE1, 0x08, 0x80, 0xBD, 0xE8
