/* DashDecomp — NODECOMPILED stub
 * Function: sub_005CCA4C
 * Virtual Address: 0x005CCA4C
 * File Offset:     0x004CCA4C
 * Size (bytes):    280
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005CCA4C
.type   sub_005CCA4C, %function

sub_005CCA4C:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 280 bytes at VA 0x005CCA4C in build/code.dec.bin
    bx lr
