/* DashDecomp — NODECOMPILED stub
 * Function: sub_005CB1BC
 * Virtual Address: 0x005CB1BC
 * File Offset:     0x004CB1BC
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005CB1BC
.type   sub_005CB1BC, %function

sub_005CB1BC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x005CB1BC in build/code.dec.bin
    bx lr
