/* DashDecomp — NODECOMPILED stub
 * Function: sub_005CFFC8
 * Virtual Address: 0x005CFFC8
 * File Offset:     0x004CFFC8
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_005CFFC8
.type   sub_005CFFC8, %function

sub_005CFFC8:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x005CFFC8 in build/code.dec.bin
    bx lr
