/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectFrogoon::initObj() [sub_0032B5D8]
 * Virtual Address: 0x0032B5D8
 * File Offset:     0x0022B5D8
 * Size (bytes):    184
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

initObj:  @ was sub_0032B5D8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 184 bytes at VA 0x0032B5D8 in build/code.dec.bin
    bx lr
