/* DashDecomp — NODECOMPILED stub
 * Function: UI::NwlytDivControlSight::findPaneByName(nw::lyt::Pane*, const sead::SafeStringBase<char>&) [sub_00152E30]
 * Virtual Address: 0x00152E30
 * File Offset:     0x00052E30
 * Size (bytes):    268
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global findPaneByName
.type   findPaneByName, %function

findPaneByName:  @ was sub_00152E30
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 268 bytes at VA 0x00152E30 in build/code.dec.bin
    bx lr
