/* DashDecomp — NODECOMPILED stub
 * Function: nw::io::RomFileStream::Close() [sub_0023A754]
 * Virtual Address: 0x0023A754
 * File Offset:     0x0013A754
 * Size (bytes):    68
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_0023A754
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 68 bytes at VA 0x0023A754 in build/code.dec.bin
    bx lr
