/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectPenguin::stateSwim() [sub_003341A8]
 * Virtual Address: 0x003341A8
 * File Offset:     0x002341A8
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global stateSwim
.type   stateSwim, %function

stateSwim:  @ was sub_003341A8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x003341A8 in build/code.dec.bin
    bx lr
