/* DashDecomp — NODECOMPILED stub
 * Function: nw::gfx::HemiSphereLight::CreateOriginalValue(nw::os::IAllocator*) [sub_002494EC]
 * Virtual Address: 0x002494EC
 * File Offset:     0x001494EC
 * Size (bytes):    240
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002494EC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 240 bytes at VA 0x002494EC in build/code.dec.bin
    bx lr
