/* DashDecomp — NODECOMPILED stub
 * Function: std::map<nn::nex::String, nn::nex::String, std::less<nn::nex::String>, nn::nex::MemAllocator<std::pair<const nn::nex::String, nn::nex::String>>>::erase(const nn::nex::String&) [sub_005D7BE8]
 * Virtual Address: 0x005D7BE8
 * File Offset:     0x004D7BE8
 * Size (bytes):    300
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_005D7BE8
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 300 bytes at VA 0x005D7BE8 in build/code.dec.bin
    bx lr
