/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::TimeAttackChart::changeOut() [sub_00494538]
 * Virtual Address: 0x00494538
 * File Offset:     0x00394538
 * Size (bytes):    128
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00494538
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 128 bytes at VA 0x00494538 in build/code.dec.bin
    bx lr
