/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::BasePage::clearRacePoint() [sub_004D0D18]
 * Virtual Address: 0x004D0D18
 * File Offset:     0x003D0D18
 * Size (bytes):    96
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004D0D18
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 96 bytes at VA 0x004D0D18 in build/code.dec.bin
    bx lr
