/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::BasePage::setRaceNo(int) [sub_004D2868]
 * Virtual Address: 0x004D2868
 * File Offset:     0x003D2868
 * Size (bytes):    48
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_004D2868
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 48 bytes at VA 0x004D2868 in build/code.dec.bin
    bx lr
