/* DashDecomp — NODECOMPILED stub
 * Function: nw::lyt::GraphicsResource::SetResource(int, void*, unsigned, bool) [sub_00264D0C]
 * Virtual Address: 0x00264D0C
 * File Offset:     0x00164D0C
 * Size (bytes):    472
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00264D0C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 472 bytes at VA 0x00264D0C in build/code.dec.bin
    bx lr
