/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectCrab::getDTIClassStatic() [sub_0031309C]
 * Virtual Address: 0x0031309C
 * File Offset:     0x0021309C
 * Size (bytes):    16
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

getDTIClassStatic:  @ was sub_0031309C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 16 bytes at VA 0x0031309C in build/code.dec.bin
    bx lr
