/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::SequenceResource::SequenceResource() [sub_0049D958]
 * Virtual Address: 0x0049D958
 * File Offset:     0x0039D958
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0049D958
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x0049D958 in build/code.dec.bin
    bx lr
