/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::GlobalDiscovery::ProcessNewSubscriber(nn::nex::DOOperation*) [sub_00199080]
 * Virtual Address: 0x00199080
 * File Offset:     0x00099080
 * Size (bytes):    236
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global ProcessNewSubscriber
.type   ProcessNewSubscriber, %function

ProcessNewSubscriber:  @ was sub_00199080
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 236 bytes at VA 0x00199080 in build/code.dec.bin
    bx lr
