/* DashDecomp — NODECOMPILED stub
 * Function: sead::Vector3CalcCtr<float>::mul(nn::math::VEC3&, const nn::math::MTX34&, const nn::math::VEC3&) [sub_00115134]
 * Virtual Address: 0x00115134
 * File Offset:     0x00015134
 * Size (bytes):    60
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00115134
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 60 bytes at VA 0x00115134 in build/code.dec.bin
    bx lr
