/* DashDecomp — NODECOMPILED stub
 * Function: sead::Vector3CalcCtr<float>::multScalar(nn::math::VEC3&, const nn::math::VEC3&, float) [sub_001151FC]
 * Virtual Address: 0x001151FC
 * File Offset:     0x000151FC
 * Size (bytes):    24
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_001151FC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 24 bytes at VA 0x001151FC in build/code.dec.bin
    bx lr
