/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::TitleDemoPage::enter(Sequence::Section::EFadeKind, unsigned) [sub_00477C88]
 * Virtual Address: 0x00477C88
 * File Offset:     0x00377C88
 * Size (bytes):    104
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

txv_validateTextureValidator:  @ was sub_00477C88
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 104 bytes at VA 0x00477C88 in build/code.dec.bin
    bx lr
