/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::JobBackEndServicesTerminate::JobBackEndServicesTerminate(unsigned, nn::nex::BackEndServices*) [sub_00154030]
 * Virtual Address: 0x00154030
 * File Offset:     0x00054030
 * Size (bytes):    108
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00154030
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 108 bytes at VA 0x00154030 in build/code.dec.bin
    bx lr
