/* DashDecomp — NODECOMPILED stub
 * Function: Util::TStateObserver<Jugem::State>::resetState() [sub_0059D928]
 * Virtual Address: 0x0059D928
 * File Offset:     0x0049D928
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0059D928
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x0059D928 in build/code.dec.bin
    bx lr
