/* DashDecomp — NODECOMPILED stub
 * Function: Sequence::LayeredSequence::LayeredSequence__sub_object() [sub_00486820]
 * Virtual Address: 0x00486820
 * File Offset:     0x00386820
 * Size (bytes):    36
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_00486820
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 36 bytes at VA 0x00486820 in build/code.dec.bin
    bx lr
