/* DashDecomp — NODECOMPILED stub
 * Function: Kart::VehicleMove::clearDriftAll() [sub_002D479C]
 * Virtual Address: 0x002D479C
 * File Offset:     0x001D479C
 * Size (bytes):    72
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002D479C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 72 bytes at VA 0x002D479C in build/code.dec.bin
    bx lr
