/* DashDecomp — NODECOMPILED stub
 * Function: Kart::VehicleMove::execEvent() [sub_002DDC34]
 * Virtual Address: 0x002DDC34
 * File Offset:     0x001DDC34
 * Size (bytes):    272
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_002DDC34
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 272 bytes at VA 0x002DDC34 in build/code.dec.bin
    bx lr
