/* DashDecomp — NODECOMPILED stub
 * Function: Kart::VehicleMove::initNrm() [sub_002DCFF0]
 * Virtual Address: 0x002DCFF0
 * File Offset:     0x001DCFF0
 * Size (bytes):    84
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002DCFF0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 84 bytes at VA 0x002DCFF0 in build/code.dec.bin
    bx lr
