/* DashDecomp — NODECOMPILED stub
 * Function: UI::LRSelect::AnimationDefine::defineAnimation() [sub_0015C928]
 * Virtual Address: 0x0015C928
 * File Offset:     0x0005C928
 * Size (bytes):    264
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global txv_validateTextureValidator
.type   txv_validateTextureValidator, %function

defineAnimation:  @ was sub_0015C928
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 264 bytes at VA 0x0015C928 in build/code.dec.bin
    bx lr
