/* DashDecomp — NODECOMPILED stub
 * Function: nn::nex::StationURL::GetURLType() const [sub_004EB86C]
 * Virtual Address: 0x004EB86C
 * File Offset:     0x003EB86C
 * Size (bytes):    28
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_004EB86C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 28 bytes at VA 0x004EB86C in build/code.dec.bin
    bx lr
