/* DashDecomp — NODECOMPILED stub
 * Function: nn::snd::CTR::Voice::SetChannelCount(int) [sub_00228314]
 * Virtual Address: 0x00228314
 * File Offset:     0x00128314
 * Size (bytes):    32
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_00228314
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 32 bytes at VA 0x00228314 in build/code.dec.bin
    bx lr
