/* DashDecomp — NODECOMPILED stub
 * Function: Item::ItemObjTail::ItemObjTail(int) [sub_002B9B70]
 * Virtual Address: 0x002B9B70
 * File Offset:     0x001B9B70
 * Size (bytes):    76
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_002B9B70
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 76 bytes at VA 0x002B9B70 in build/code.dec.bin
    bx lr
