/* DashDecomp — NODECOMPILED stub
 * Function: nw::snd::SoundStartable::HoldSound(nw::snd::SoundHandle*, unsigned, const nw::snd::SoundStartable::StartInfo*) [sub_0026CC2C]
 * Virtual Address: 0x0026CC2C
 * File Offset:     0x0016CC2C
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0026CC2C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x0026CC2C in build/code.dec.bin
    bx lr
