/* DashDecomp — NODECOMPILED stub
 * Function: Kart::KartConstructInfoAccessor::getBackShaftOffset() [sub_002E9A18]
 * Virtual Address: 0x002E9A18
 * File Offset:     0x001E9A18
 * Size (bytes):    516
 *
 * Status: NODECOMPILED 🔴
 * This stub was auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global vldtr_validateAllState
.type   vldtr_validateAllState, %function

vldtr_validateAllState:  @ was sub_002E9A18
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 516 bytes at VA 0x002E9A18 in build/code.dec.bin
    bx lr
