/* DashDecomp — NODECOMPILED stub
 * Function: sub_00590CFC
 * Virtual Address: 0x00590CFC
 * File Offset:     0x00490CFC
 * Size (bytes):    116
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global sub_00590CFC
.type   sub_00590CFC, %function

sub_00590CFC:
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 116 bytes at VA 0x00590CFC in build/code.dec.bin
    bx lr
