/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectWiiEscalator::stateInitDown() [sub_00370FF0]
 * Virtual Address: 0x00370FF0
 * File Offset:     0x00270FF0
 * Size (bytes):    212
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global stateInitDown
.type   stateInitDown, %function

stateInitDown:  @ was sub_00370FF0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 212 bytes at VA 0x00370FF0 in build/code.dec.bin
    bx lr
