/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectPipeBase::createOriginalCollision(Field::SObjectCollisionSet*) [sub_003420D0]
 * Virtual Address: 0x003420D0
 * File Offset:     0x002420D0
 * Size (bytes):    4
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global AscendingPingSort
.type   AscendingPingSort, %function

AscendingPingSort:  @ was sub_003420D0
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 4 bytes at VA 0x003420D0 in build/code.dec.bin
    bx lr
