/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectPipeBase::getDTIClassStatic() [sub_00341E7C]
 * Virtual Address: 0x00341E7C
 * File Offset:     0x00241E7C
 * Size (bytes):    168
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global getDTIClassStatic
.type   getDTIClassStatic, %function

getDTIClassStatic:  @ was sub_00341E7C
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 168 bytes at VA 0x00341E7C in build/code.dec.bin
    bx lr
