/* DashDecomp — NODECOMPILED stub
 * Function: Field::ObjectFlash::getDTIClassStatic() [sub_00315DFC]
 * Virtual Address: 0x00315DFC
 * File Offset:     0x00215DFC
 * Size (bytes):    844
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

getDTIClassStatic:  @ was sub_00315DFC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 844 bytes at VA 0x00315DFC in build/code.dec.bin
    bx lr
