/* DashDecomp — NODECOMPILED stub
 * Function: RaceSys::LogRecorder::addValue(RaceSys::LogRecorder::EValueType, int) [sub_0045D9FC]
 * Virtual Address: 0x0045D9FC
 * File Offset:     0x0035D9FC
 * Size (bytes):    104
 *
 * Status: NODECOMPILED 🔴
 * Auto-generated by tools/regenerate_stubs.py
 * Symbol source: Ghidra auto-analysis
 *
 * To decompile: write matching C++ and replace this file with your .cpp in src/
 */

.section .text
.global quazal_crc32
.type   quazal_crc32, %function

quazal_crc32:  @ was sub_0045D9FC
    @ NODECOMPILED — assembly stub, not yet decompiled
    @ Size: 104 bytes at VA 0x0045D9FC in build/code.dec.bin
    bx lr
